lib/config/routes.dart
lib/pangea/guard/p_vguard.dart
lib/pangea/pages/p_user_age/p_user_age_view.dart
lib/widgets/matrix.dart
pubspec.lock
pubspec.yaml

Replaces flutter's built in date picker with syncfusion_flutter_datepicker, which is more user-friendly

New date picker

---

lib/pages/chat_list/space_view.dart
lib/pangea/extensions/sync_update_extension.dart

- Added extension to SyncUpdate to filter for room join, invite, leave, and space child events
- Used filtering functions to determine when to refresh space view to auto-update without manual refresh
- Updated items within space view to solve errors with rejoining left rooms

Refresh space view based on filtered events

---

lib/pages/chat/chat.dart

When a message is selected, it only shows the edit option if it's a text message

Non-text messages cannot be edited

---

lib/pages/chat_list/space_view.dart

When user selects a room, checks that the user is a member of the room and has admin privileges before showing them the option to remove room from space.

Only admins can remove a room from a space

---

lib/config/routes.dart
lib/pages/chat_list/start_chat_fab.dart
lib/pages/new_group/new_group.dart

When a user creates a new group from inside a class, the space ID will be stored via query instead of path. Fixes issue where user had to back out of new group screen twice to leave.

New group uses query to store space ID 

---

lib/pages/chat/events/message_content.dart
lib/pangea/widgets/chat/message_toolbar.dart
lib/pangea/widgets/chat/message_translation_card.dart
lib/pangea/widgets/igc/pangea_rich_text.dart

Stopped FlutterError from throwing when toolbar closed on its own
Kept translated word length from affecting Define and Translate in toolbar
Made autoplay default value in toolbar false

Fixing toolbar bugs for newly-sent messages

---

lib/pages/chat/chat_view.dart

Copy option doesn't show for when non-text message or multiple messages are selected

Situationally remove copy option on selection

---

lib/pages/invitation_selection/invitation_selection_view.dart

When pressing the back button to exit the 'invite contact' page, return to chat/exchange/class details

Invitation page returns to details

---

assets/l10n/intl_en.arb
lib/pangea/controllers/user_controller.dart
lib/pangea/models/user_model.dart
lib/pangea/utils/instructions.dart
lib/pangea/widgets/chat/message_speech_to_text_card.dart
lib/pangea/widgets/common/icon_number_widget.dart
needed-translations.txt

When the user presses a button without an associated text label or press-activated action, instructions will show explaining how to view tooltips.
So far, the only situation I've found that matches this criteria is Accuracy/Words per minute in the speech to text toolbar. Let me know if you find anywhere else for me to add it.

Added instructions for tooltips

---

lib/pages/settings/settings.dart

When a user edits their displayname, then leaves and returns to settings, it will show the new displayname.

Edited displayname shows when return to settings

---

lib/pages/chat/chat.dart

Check for eventId match instead of exact match when selecting/deselecting, so that duplicate selection cannot occur if an event parameter changes

No duplicate selection

---

lib/pangea/widgets/chat/message_toolbar.dart

If the toolbar is opened for a message on the top half of the screen, it will open downward, so that it isn't clipped by the top of the screen.

Toolbar stay onscreen

---

assets/l10n/intl_en.arb
lib/pages/chat_list/chat_list.dart
lib/pangea/extensions/pangea_room_extension/children_and_parents_extension.dart
lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart
lib/pangea/widgets/class/add_space_toggles.dart

When viewing possible parents (in Add to Space menu, or in class details page), the potential child cannot be added as a child to itself, or to its descendants. 
(not implemented yet) If the user does not have adequate permissions, the option to add to that space will be grayed out, and will notify the user if they attempt to click on it.

Limit add to space

---

lib/pangea/extensions/pangea_room_extension/events_extension.dart
lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart

Archiving/leaving spaces is applied recursively to any subspaces. Previously, the subspaces were archived like a normal chat would be archived.

Archive subspaces properly

---

lib/pangea/pages/find_partner/find_partner_view.dart

Remove domain name from names of potential conversation partners. If a name is still too long, shortens name with ellipses, to prevent overflow.

Fix conversation partner search list overflow

---

lib/pangea/widgets/chat/message_translation_card.dart

Only show toolbar translate warning when the originalSent language equals the user's L1, or if the translated text is the same as the original message text

Changes criteria for showing translate warning

---

lib/pages/chat/events/audio_player.dart

Decrease unecessary padding in toolbar audio tab
I haven't gotten the overflow issue myself, so I wasn't able to test whether this resolved the error.

Fix audio overflow

---

lib/pages/chat/chat.dart

Ignores 'PangeaWarningError: Pangea Warning Error: Timeline is null or empty' error

Silences null timeline error

---

lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_body.dart

When a user logs in, the chat list is shown as soon as the account's rooms are loaded.
Also, moves less important syncs (analytics, etc) to run in background.

Chat list is shown when rooms are loaded

---

lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart

The Report User button (accessed by selecting another user's avatar in a chat) can not be used to report a user, since it doesn't have an associated message to report. 
Since the button doesn't work for its intended purpose, I hid it. 
Users can still be reported by reporting the offensive message directly.

Remove option to report user

---

lib/pangea/pages/settings_learning/settings_learning_view.dart

The Public Profile setting is no longer relevant, since the conversation partner functionality was removed.

Hide public profile toggle in learning settings

---

lib/pangea/controllers/message_analytics_controller.dart

Fixes #1038
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pangeachat/client/pull/1039?shareId=f33c0f89-b61a-438c-9408-b997154b8a2e).

Fix hidden word listening activity to limit sequences to 2 words

---

lib/pangea/choreographer/widgets/it_bar.dart

When the user presses the IGC button and brings up the IT bar, a loading indicator is shown until possible choices are done fetching.

Adds loading indicator when waiting for IGC options

---

lib/pages/chat/events/message.dart
lib/pangea/activity_planner/activity_plan_message.dart
lib/pangea/toolbar/widgets/message_audio_card.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/overlay_message.dart

chore: update link text color in dark mode

---

lib/pangea/learning_settings/pages/settings_learning_view.dart
lib/pangea/learning_settings/widgets/country_picker_tile.dart
lib/pangea/learning_settings/widgets/p_language_dropdown.dart

fix: make learning settings dropdowns stand out against background

---

lib/pangea/toolbar/widgets/practice_activity/emoji_practice_button.dart

fix: add back emoji button

---

lib/pangea/analytics_details_popup/analytics_details_popup.dart
lib/pangea/analytics_summary/progress_indicator.dart

fix: switch vocab / grammar buttons to use icon and text

---

lib/pages/chat/input_bar.dart

chore: revert deleting selection area in input bar

---

lib/pangea/extensions/room_settings_extension.dart

fix: force room settings header onto one line with ellipsis for overflow

---

lib/pangea/subscription/controllers/subscription_controller.dart
lib/pangea/subscription/pages/change_subscription.dart
lib/pangea/subscription/pages/settings_subscription.dart
lib/widgets/future_loading_dialog.dart

chore: show loading indicator and don't hide button on subscription page

---

lib/l10n/intl_en.arb
lib/pages/chat_list/chat_list_body.dart
lib/pangea/common/controllers/pangea_controller.dart

Removed reference to button that no longer shows in prompt when user is not in any rooms
- [ ] Android

Update no room prompt

---

lib/pangea/toolbar/widgets/reading_assistance_content.dart

Adds a small, primary color border around the outside of the zoomed in word card so it stands out against the background.
- [ ] Android
- [ ] iOS

chore: add border around word card for emphasis

---

lib/pages/chat_search/chat_search_message_tab.dart

When a user searches the chat for a message, filters the following from the results:
- non-message events
- non-text messages
- [ ] Android
- [ ] …

Only shows text messages in chat search

---

lib/pages/chat/chat.dart

[This PR](https://github.com/pangeachat/client/pull/3373) sets pinned events every time a message is redacted, which leads to a lot of unnecessary network requests.
Minimize network requests by checking whether a redacted message is pinned before unpinning it
- [ ] Every new feature in the app or the build system has a strategy how …

Only change pin list if redacted event is pinned

---

lib/pages/chat/events/pangea_message_reactions.dart

and loading symbol is always placed at the very end, not the end of the first row.
- [ ] Android
- [ ] iOS

fix: row two and more of reactions add normally

---

lib/pages/chat/chat.dart
lib/pages/chat/events/message.dart

Calls the same unpin function from both places you can unpin, so the same dialog shows and the pin highlight is removed.
- [ ] Android
- [ ] iOS
- …

3607 pinned message highlight persists after unpinning
