lib/pages/chat/chat_view.dart

chore: don't show input bar in abandoned DM room

---

lib/config/app_config.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart

chore: adjust scrolling / positioning for new toolbar buttons columns

---

lib/pangea/analytics_details_popup/morph_meaning_widget.dart

chore: fix expanded widget in morph meaning widget

---

lib/config/routes.dart
lib/pages/chat_list/chat_list_header.dart
lib/pages/chat_list/client_chooser_button.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/analytics_summary/learning_settings_button.dart

chore: remove popup button in menu, go directly to settings

---

lib/config/routes.dart

chore: replace empty page in settings with activity selection page

---

assets/l10n/intl_en.arb

chore: update activity suggestion launch button copy

---

lib/pangea/activity_suggestions/activity_suggestion_card_row.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: blur background on activity dialog, increase dialog text sizes

---

lib/pangea/toolbar/widgets/message_token_text.dart

chore: fix newline rendering in non-HTML formatted messages

---

lib/utils/background_push.dart

chore: wrap badge setting in try-catch block

---

lib/pages/chat/chat.dart
lib/utils/file_selector.dart

chore: open gallery on select image

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_speech_to_text_card.dart

2140-toolbar-should-not-show-audio-for-audio-messages

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart

2144-make-activity-suggestion-cards-scroll-horizontally-on-wide-screens

---

lib/config/themes.dart
lib/pages/chat/events/html_message.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/analytics_details_popup/analytics_details_popup_content.dart
lib/pangea/analytics_details_popup/lemma_usage_dots.dart
lib/pangea/analytics_details_popup/lemma_use_example_messages.dart
lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_details_popup/morph_details_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_details_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_tile.dart
lib/pangea/analytics_misc/text_loading_shimmer.dart
lib/pangea/choreographer/widgets/igc/card_header.dart
lib/pangea/choreographer/widgets/igc/paywall_card.dart
lib/pangea/choreographer/widgets/igc/span_card.dart
lib/pangea/choreographer/widgets/igc/why_button.dart
lib/pangea/choreographer/widgets/it_shimmer.dart
lib/pangea/choreographer/widgets/language_permissions_warning_buttons.dart
lib/pangea/constructs/construct_level_enum.dart
lib/pangea/subscription/widgets/subscription_options.dart
lib/pangea/subscription/widgets/subscription_snackbar.dart
lib/pangea/toolbar/reading_assistance_input_row/message_emoji_choice_item.dart
lib/pangea/toolbar/reading_assistance_input_row/word_emoji_choice.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/message_unsubscribed_card.dart
lib/pangea/toolbar/widgets/missing_voice_button.dart
lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart

2138-make-user-choice-of-color-consistently-applied

---

assets/l10n/intl_en.arb
lib/config/routes.dart
lib/pages/chat/chat.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/suggestions_page.dart
lib/pangea/common/widgets/pressable_button.dart

2136 activity suggestions feedback

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: hide room capacity button in DMs

---

lib/pages/chat/chat_event_list.dart
lib/pages/chat/events/html_message.dart
lib/pages/chat/events/message.dart
lib/pangea/activity_planner/activity_plan_message.dart

chore: allow users to select activity messages

---

lib/pages/chat/chat.dart
lib/pangea/chat/widgets/chat_floating_action_button.dart
lib/pangea/chat/widgets/chat_view_background.dart
lib/pangea/chat/widgets/input_bar_wrapper.dart
lib/pangea/choreographer/controllers/choreographer.dart
lib/pangea/choreographer/widgets/it_bar.dart
lib/pangea/choreographer/widgets/send_button.dart
lib/pangea/choreographer/widgets/start_igc_button.dart
lib/pangea/user/controllers/user_controller.dart
lib/pangea/writing_assistance/writing_assistance_input_row.dart

chore: refresh choreographer on change learning settings

---

lib/pages/chat/events/message_content.dart

chore: don't allow users to click tokens in activity messages

---

lib/pages/new_group/new_group_view.dart

chore: disable both toggles while new space creation is loading

---

lib/pangea/analytics_details_popup/analytics_details_popup_content.dart
lib/pangea/analytics_details_popup/lemma_usage_dots.dart
lib/pangea/analytics_details_popup/vocab_analytics_details_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_tile.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_view.dart

2141 empty vocab entry

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/suggestions_page.dart

chore: improvements to activity suggestion UI on mobile

---

lib/pangea/analytics_details_popup/vocab_analytics_list_tile.dart
lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart

chore: improve readability of text in analytics popups

---

lib/pages/chat_members/chat_members.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/widgets/public_room_bottom_sheet.dart

chore: refresh chat participant list page on participants list change

---

lib/pangea/activity_suggestions/suggestions_page.dart

chore: adjust header text size on activity suggestions page

---

lib/pangea/activity_planner/activity_list_view.dart
lib/pangea/activity_planner/activity_plan_message.dart
lib/pangea/activity_planner/activity_plan_page_launch_icon_button.dart
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_suggestions/activity_suggestions_constants.dart
lib/pangea/analytics_summary/progress_indicators_enum.dart

chore: add images to activity planner page

---

lib/pangea/common/utils/error_handler.dart
lib/pangea/subscription/controllers/subscription_controller.dart
lib/pangea/subscription/models/base_subscription_info.dart

chore: better error logging if subscription info is null

---

lib/pangea/choreographer/repo/full_text_translation_repo.dart
lib/pangea/choreographer/widgets/it_feedback_card.dart

chore: fix for null check error in getFeedback

---

lib/pangea/subscription/widgets/subscription_snackbar.dart

chore: update subscription snackbar link color

---

lib/pangea/activity_suggestions/create_chat_card.dart
lib/pangea/common/widgets/customized_svg.dart

chore: make plus icon color match theme

---

lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: increase text size in activity suggestion dialog

---

lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_mode_dynamic_zone.dart
lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_mode_select.dart
lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_settings_form.dart
lib/pangea/chat_settings/widgets/language_level_dropdown.dart
lib/pangea/common/widgets/dropdown_text_button.dart
lib/pangea/learning_settings/widgets/country_picker_tile.dart
lib/pangea/learning_settings/widgets/p_language_dropdown.dart

chore: highlight selected item in dropdowns

---

assets/l10n/intl_en.arb
lib/pages/invitation_selection/invitation_selection.dart
lib/pages/invitation_selection/invitation_selection_view.dart
lib/pangea/chat_settings/constants/room_settings_constants.dart
lib/pangea/chat_settings/widgets/refer_friends_dialog.dart

refactor: invite page redesign

---

lib/config/routes.dart
lib/pages/settings/settings_view.dart
lib/pangea/learning_settings/pages/settings_learning.dart
lib/pangea/learning_settings/pages/settings_learning_view.dart

chore: add learning settings to general settings

---

lib/config/routes.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/suggestions_page.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/layouts/bottom_nav_layout.dart

chore: some UI/UX to bottom nav bar navigation

---

assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/chat/utils/unlocked_morphs_snackbar.dart

feat: show unlocked constructs snackbar

---

lib/pangea/activity_planner/activity_list_view.dart

chore: check if mounted before setting state in async function

---

lib/pangea/subscription/controllers/subscription_controller.dart

chore: improve logic for when to show subscription snackbar

---

lib/pangea/learning_settings/constants/language_constants.dart
lib/pangea/learning_settings/repo/language_repo.dart

chore: add hardcoded fallback language list

---

lib/pangea/toolbar/widgets/message_selection_positioner.dart

fix: hide duplicate tooltip

---

lib/config/app_config.dart
lib/pages/chat/chat.dart
lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_details_popup/morph_meaning_widget.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/chat_list/utils/get_chat_list_item_subtitle.dart
lib/pangea/choreographer/widgets/igc/card_header.dart
lib/pangea/events/models/pangea_token_model.dart
lib/pangea/events/utils/message_text_util.dart
lib/pangea/instructions/instructions_inline_tooltip.dart
lib/pangea/lemmas/lemma_emoji_row.dart
lib/pangea/message_token_text/message_token_button.dart
lib/pangea/practice_activities/message_analytics_controller.dart
lib/pangea/practice_activities/message_analytics_entry.dart
lib/pangea/practice_activities/target_tokens_and_activity_type.dart
lib/pangea/toolbar/reading_assistance_input_row/message_match_activity.dart
lib/pangea/toolbar/reading_assistance_input_row/message_match_activity_item.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice_item.dart
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart
lib/pangea/toolbar/widgets/message_audio_card.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/toolbar_button_column.dart
lib/pangea/toolbar/widgets/word_zoom/morphological_list_item.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

formatting

---

lib/pages/chat/chat.dart
lib/pangea/choreographer/widgets/choice_animation.dart
lib/pangea/choreographer/widgets/choice_array.dart
lib/pangea/common/utils/overlay.dart
lib/pangea/toolbar/reading_assistance_input_row/message_match_activity.dart
lib/pangea/toolbar/reading_assistance_input_row/message_match_activity_item.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart

2220 separate animation logic from choice array and apply to messge match activity

---

lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_planner/activity_plan_model.dart
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_planner/activity_planner_page_appbar.dart
lib/pangea/activity_planner/bookmarked_activities_repo.dart
lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_planner/generated_activity_list.dart
lib/pangea/activity_planner/new_activity_form.dart
lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart

feat: featured activities page and new activity planner navigation

---

lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_settings_form.dart

chore: add decoration text to bot settings language dropdown

---

assets/l10n/intl_en.arb
lib/config/routes.dart
lib/pages/invitation_selection/invitation_selection_view.dart
lib/pages/new_group/new_group.dart
lib/pages/new_group/new_group_view.dart
lib/pangea/activity_generator/activity_generator.dart
lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_planner/activity_planner_page_appbar.dart
lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/make_activity_card.dart
lib/widgets/layouts/max_width_body.dart

2253 activity planner feedback

---

lib/pangea/analytics_details_popup/morph_details_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_details_view.dart
lib/pangea/lemmas/lemma_emoji_row.dart
lib/pangea/toolbar/widgets/practice_activity/word_text_with_audio_button.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart

chore: updates to sizing and spacing in vocab details popup

---

assets/l10n/intl_en.arb

chore: updated bookmarks copy

---

lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/choreographer/controllers/it_controller.dart
lib/pangea/choreographer/controllers/span_data_controller.dart
lib/pangea/choreographer/widgets/igc/span_card.dart
lib/pangea/choreographer/widgets/start_igc_button.dart

2233 usability test todos

---

lib/pangea/learning_settings/pages/settings_learning_view.dart

chore: show back button in learning settings page

---

lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_view.dart
lib/pangea/analytics_misc/constructs_model.dart
lib/pangea/choreographer/widgets/it_bar.dart
lib/pangea/instructions/instructions_inline_tooltip.dart
lib/pangea/practice_activities/emoji_activity_generator.dart

chore: don't hide inline tooltip icons until tooltip is closed

---

assets/l10n/intl_en.arb
lib/pages/new_group/new_group.dart
lib/pages/new_group/new_group_view.dart
lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/create_chat_card.dart
lib/pangea/activity_suggestions/make_activity_card.dart
lib/pangea/common/widgets/pressable_button.dart
lib/pangea/login/widgets/full_width_button.dart

2280 new chat page and activity planner refine

---

lib/config/app_config.dart
lib/pages/chat/chat.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/chat/utils/unlocked_morphs_snackbar.dart
lib/pangea/common/utils/any_state_holder.dart
lib/pangea/common/utils/overlay.dart
lib/pangea/instructions/instructions_inline_tooltip.dart
lib/pangea/lemmas/lemma_emoji_row.dart
lib/pangea/practice_activities/practice_activity_model.dart
lib/pangea/practice_activities/practice_generation_repo.dart
lib/pangea/practice_activities/practice_match.dart
lib/pangea/practice_activities/practice_record.dart
lib/pangea/practice_activities/practice_target.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
pubspec.lock

refactor: move construct notifications to the top of the screen

---

lib/pangea/chat/widgets/pangea_chat_input_row.dart
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart

chore: decouple selected message list from chat input row rendering

---

assets/l10n/intl_en.arb
lib/pangea/events/utils/report_message.dart

chore: move message reporting copy to localizations file

---

lib/pangea/analytics_misc/get_analytics_controller.dart

chore: disable level up summary

---

lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: replace image error icon with empty box

---

lib/pangea/activity_planner/activity_plan_model.dart

chore: force vocab onto newline in activity markdown

---

lib/pangea/chat_list/utils/get_chat_list_item_subtitle.dart
lib/pangea/toolbar/widgets/message_token_text.dart

chore: don't change message text size for chat list item subtitles

---

lib/pangea/toolbar/widgets/message_token_text.dart

fix: don't use custom sizing for subtitles

---

lib/pages/chat/events/message_content.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/practice_activities/practice_target.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart
lib/pangea/toolbar/widgets/word_zoom/morphological_list_item.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: formatting

---

assets/l10n/intl_en.arb
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/suggestions_page.dart
lib/pangea/public_spaces/public_space_card.dart
lib/pangea/public_spaces/public_spaces_area.dart

feat: public spaces on homepage

---

lib/pangea/common/utils/error_handler.dart

chore: uncomment sentry initialization

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/public_spaces/public_spaces_area.dart

fix: remove rogue expanded widgets

---

lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_settings.dart
lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_settings_form.dart

chore: simplify bot settings

---

lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_suggestions/activity_suggestion_card.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/public_spaces/public_space_card.dart

Public space click

---

lib/pangea/chat/utils/unlocked_morphs_snackbar.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart

chore: wrap construct notification in safe area

---

lib/pages/chat/input_bar.dart
lib/pangea/chat/widgets/pangea_chat_input_row.dart

chore: make input bar hint text shrink to fit

---

lib/pages/chat/chat_input_row.dart
lib/pages/chat_list/chat_list.dart
lib/pages/new_group/new_group.dart
lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: use query parameter to set chat list filter

---

lib/pages/chat_list/chat_list.dart
lib/pangea/common/widgets/customized_svg.dart

chore: update svg when svg url changes

---

assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pangea/instructions/instructions_enum.dart

chore: add warning popup to empty chats

---

assets/l10n/intl_en.arb
lib/pages/chat_list/chat_list_body.dart
lib/pages/chat_list/space_view.dart
lib/pangea/public_spaces/pangea_public_room_bottom_sheet.dart
lib/pangea/public_spaces/public_space_card.dart
lib/utils/url_launcher.dart

refactor: public room bottom sheet redesign

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/user/controllers/user_controller.dart

chore: reload activity suggestions on language update

---

lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: make image in suggestion dialog fill width

---

lib/pangea/toolbar/widgets/message_token_text.dart

fix: dispose text painter to prevent memory leak

---

lib/pages/settings_style/settings_style_view.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/widgets/matrix.dart

chore: disable custom message text sizing

---

lib/pangea/choreographer/controllers/choreographer.dart
lib/pangea/choreographer/models/choreo_record.dart
lib/pangea/choreographer/utils/input_paste_listener.dart
lib/pangea/events/models/representation_content_model.dart

feat: initial work to prevent giving points for copy-pasted text

---

lib/pangea/activity_generator/activity_generator.dart
lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart
lib/pangea/practice_activities/practice_match.dart
lib/pangea/practice_activities/practice_selection.dart
lib/pangea/practice_activities/practice_selection_repo.dart
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart

2364 on chat creation with activity if no room image set activity image

---

lib/pangea/toolbar/widgets/message_unsubscribed_card.dart
lib/pangea/toolbar/widgets/reading_assistance_content.dart

chore: constrain width of unsubscribed card

---

lib/pangea/events/utils/report_message.dart
lib/pangea/instructions/empty_chat_popup.dart
lib/pangea/toolbar/widgets/overlay_header.dart

chore: fix dialogs in report offensive message flow

---

lib/pages/chat_list/chat_list.dart
lib/pangea/analytics_misc/level_up.dart

chore: fix off-center close button in level up notifications

---

lib/widgets/avatar.dart

chore: don't show presence indicator on small avatars

---

lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: give max height to image in activity suggestion dialog

---

lib/pangea/public_spaces/pangea_public_room_bottom_sheet.dart
lib/pangea/spaces/controllers/space_controller.dart
lib/widgets/public_room_bottom_sheet.dart

chore: when navigating to space details, always open space view

---

lib/pages/chat/events/html_message.dart
lib/pangea/chat_list/utils/get_chat_list_item_subtitle.dart

chore: fix vertical alignment of tokens in HTML-formatted messages

---

lib/pangea/activity_planner/activity_list_view.dart
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_planner/bookmarked_activities_repo.dart

fix: allow users to launch bookmarked activities

---

lib/config/app_config.dart
lib/pages/chat/events/html_message.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/reactions_picker.dart
lib/pangea/common/utils/any_state_holder.dart
lib/pangea/common/widgets/customized_svg.dart
lib/pangea/events/utils/message_text_util.dart
lib/pangea/morphs/morph_features_enum.dart
lib/pangea/toolbar/enums/reading_assistance_mode_enum.dart
lib/pangea/toolbar/reading_assistance_input_row/overlay_footer.dart
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart
lib/pangea/toolbar/utils/token_rendering_util.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/overlay_center_content.dart
lib/pangea/toolbar/widgets/overlay_message.dart

refactor: separate token and message reading assistance modes

---

lib/config/app_config.dart
lib/pages/chat/chat.dart
lib/pages/chat/reactions_picker.dart
lib/pangea/chat/widgets/pangea_chat_input_row.dart
lib/pangea/toolbar/reading_assistance_input_row/overlay_footer.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/toolbar_button_column.dart

2421 reading assistance mode split feedback from will

---

lib/pages/new_group/new_group_view.dart

Added 'JoinByCode' button on new group view

---

lib/pangea/choreographer/widgets/igc/card_error_widget.dart
lib/pangea/events/event_wrappers/pangea_message_event.dart
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart

chore: only show STT for .wav audio messages

---

assets/l10n/intl_en.arb
lib/pangea/public_spaces/pangea_public_room_bottom_sheet.dart

2426-space-popup-tweaks

---

lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/analytics_misc/get_analytics_controller.dart

chore: add new construct ID info to analytics stream

---

lib/pangea/public_spaces/pangea_public_room_bottom_sheet.dart

chore: fix public space avatar loading

---

lib/pangea/activity_generator/activity_generator.dart
lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_planner/activity_plan_model.dart
lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart

chore: fixes for editting / bookmarking of activities

---

lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/common/widgets/customized_svg.dart

2411 the tense icon is too dark and the boxes stick together

---

android/app/build.gradle
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
android/settings.gradle
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

build: update gradle version

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: hide back button in space details page

---

lib/pages/chat/chat.dart
lib/pangea/analytics_misc/gain_points_animation.dart
lib/pangea/message_token_text/message_token_button.dart
lib/pangea/practice_activities/practice_target.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice_item.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_card.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart

2455 reading assistance feedback from linh

---

lib/pages/settings_style/settings_style_view.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/widgets/matrix.dart

chore: revert changes to text sizing

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/reading_assistance_content.dart

chore: prevent overflow of reading assistance content popup

---

lib/pages/chat/chat.dart

chore: close all overlays on leave chat page

---

lib/pangea/practice_activities/practice_selection_repo.dart

chore: return a null practice entry if it does not match user's L2

---

lib/pages/chat/events/html_message.dart
lib/pangea/choreographer/widgets/choice_animation.dart
lib/pangea/message_token_text/message_token_button.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_card.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/practice_activity/practice_activity_card.dart

2464 the empty space above the message is not pleasing   any solution

---

pubspec.lock
pubspec.yaml

use non caching space hierarchy

---

pubspec.lock
pubspec.yaml

fix: use matrix sdk branch with space caching turned off

---

assets/l10n/intl_en.arb
lib/pangea/analytics_details_popup/analytics_details_popup.dart
lib/pangea/chat/utils/unlocked_morphs_snackbar.dart

2495 show grammar notification longer 15 seconds and add expand

---

lib/pangea/analytics_misc/constructs_model.dart
lib/pangea/analytics_summary/level_bar_popup.dart

chore: give neutral construct uses a neutral color

---

lib/pangea/choreographer/controllers/igc_controller.dart
lib/pangea/choreographer/models/igc_text_data_model.dart
lib/pangea/choreographer/models/pangea_match_model.dart
lib/pangea/choreographer/widgets/igc/pangea_text_controller.dart
lib/pangea/choreographer/widgets/igc/span_card.dart
lib/pangea/common/utils/any_state_holder.dart
lib/pangea/common/utils/overlay.dart

chore: highlight selected span during IGC

---

lib/pangea/choreographer/controllers/igc_controller.dart
lib/pangea/choreographer/controllers/it_controller.dart
lib/pangea/choreographer/widgets/igc/pangea_text_controller.dart
lib/pangea/choreographer/widgets/it_bar.dart
lib/pangea/common/utils/any_state_holder.dart
lib/pangea/common/utils/overlay.dart

2505 have to click on other options multiple times for the click to go through after selecting an incorrect choice in it

---

lib/pangea/chat/utils/unlocked_morphs_snackbar.dart

chore: fix overflow in construct notification

---

pubspec.yaml

build: bump version

---

assets/l10n/intl_en.arb
lib/pages/chat/events/html_message.dart
lib/pangea/analytics_details_popup/morph_meaning_widget.dart
lib/pangea/message_token_text/message_token_button.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice_item.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_token_text.dart
lib/pangea/toolbar/widgets/toolbar_button_column.dart

2506 feedback on the new word card and message activities

---

lib/pangea/analytics_details_popup/morph_meaning_widget.dart
lib/pangea/choreographer/widgets/choice_array.dart
lib/pangea/choreographer/widgets/igc/span_card.dart
lib/pangea/choreographer/widgets/it_bar.dart
lib/pangea/learning_settings/pages/settings_learning.dart
lib/pangea/toolbar/controllers/tts_controller.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart
lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice_item.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/practice_activity/multiple_choice_activity.dart
lib/pangea/toolbar/widgets/practice_activity/word_audio_button.dart
lib/pangea/toolbar/widgets/practice_activity/word_text_with_audio_button.dart
lib/pangea/toolbar/widgets/toolbar_button_column.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: require passing of langCode to TTS, log langCode

---

lib/pangea/choreographer/controllers/choreographer.dart
lib/pangea/choreographer/models/igc_text_data_model.dart
lib/pangea/choreographer/widgets/igc/autocorrect_popup.dart
lib/pangea/choreographer/widgets/igc/pangea_text_controller.dart

chore: allow users to undo autocorrection of normalization errors

---

lib/pangea/toolbar/reading_assistance_input_row/practice_match_card.dart
lib/pangea/toolbar/reading_assistance_input_row/practice_match_item.dart

chore: don't cut off emoji buttons into reading assistance input bar

---

lib/config/app_config.dart
lib/pangea/toolbar/enums/reading_assistance_mode_enum.dart
lib/pangea/toolbar/reading_assistance_input_row/overlay_footer.dart
lib/pangea/toolbar/utils/token_rendering_util.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/overlay_center_content.dart
lib/pangea/toolbar/widgets/practice_mode_buttons.dart
lib/pangea/toolbar/widgets/select_mode_buttons.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart

2507 still requesting unlocking translation faster

---

lib/pangea/choreographer/widgets/igc/autocorrect_popup.dart

chore: wrap autocorrect popup in material widget

---

lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/message_speech_to_text_card.dart
lib/pangea/toolbar/widgets/overlay_message.dart

chore: move STT into message bubble

---

lib/pangea/lemmas/construct_xp_widget.dart
lib/pangea/morphs/edit_morph_widget.dart
lib/pangea/toolbar/widgets/reading_assistance_content.dart
lib/pangea/toolbar/widgets/word_zoom/morphological_list_item.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: move morph editting into morph popup

---

lib/pages/invitation_selection/invitation_selection_view.dart
lib/pangea/chat_settings/widgets/class_invitation_buttons.dart

chore: add button to copy invite code/link to space invite page

---

assets/l10n/intl_en.arb
lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart

chore: add instruction to empty reading assistance input bar

---

lib/config/app_config.dart
lib/pages/chat_list/chat_list.dart

chore: set all as default filter and remove spaces from all tab

---

lib/pages/chat_list/chat_list_view.dart

chore: hide space tab button in search mode

---

assets/l10n/intl_en.arb
lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart

chore: update knock copy to say space instead of chat

---

lib/pages/chat_list/chat_list_body.dart

chore: hide groups tab if not separating DMs and groups

---

lib/pangea/toolbar/widgets/message_selection_positioner.dart

chore: account for open details column in message positioner

---

lib/pangea/chat_settings/widgets/language_level_dropdown.dart

chore: increase height of menu item in cefr level dropdown on mobile

---

lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/chat_settings/widgets/visibility_toggle.dart

chore: show visibility toggle loading, standardize level calculation

---

lib/pages/chat/chat.dart
lib/pages/chat/input_bar.dart

chore: on error in message send, clear fake event

---

lib/pangea/login/widgets/full_width_button.dart

chore: remove strict height constraint on login/signin text input fields

---

lib/pangea/morphs/morph_meaning/morph_info_repo.dart
lib/pangea/toolbar/widgets/word_zoom/morphological_list_item.dart

chore: fix text overflow in morph meaning popup

---

lib/pangea/toolbar/widgets/message_selection_positioner.dart

chore: account for selection buttons height in overlay positioning

---

lib/pages/chat/chat.dart
lib/pangea/choreographer/controllers/igc_controller.dart
lib/pangea/choreographer/widgets/igc/pangea_text_controller.dart
lib/pangea/common/utils/any_state_holder.dart

chore: close level up / constructs notifications on close chat

---

lib/pages/chat/chat_app_bar_title.dart
lib/pages/chat/events/room_creation_state_event.dart
lib/pages/chat/seen_by_row.dart
lib/pages/chat/typing_indicators.dart
lib/pages/chat_details/chat_details_view.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_item.dart
lib/pages/chat_list/space_view.dart
lib/pages/chat_list/status_msg_list.dart
lib/pages/chat_search/chat_search_message_tab.dart
lib/pages/settings/settings_view.dart
lib/pages/settings_ignore_list/settings_ignore_list_view.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/widgets/avatar.dart
lib/widgets/profile_bottom_sheet.dart

chore: use separate argument for determining bot avatar

---

lib/pangea/toolbar/widgets/practice_activity/word_audio_button.dart
lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: fix positioning in word zoom widget header buttons

---

lib/pangea/analytics_misc/level_display_name.dart
lib/pangea/user/controllers/user_controller.dart

chore: return empty profile for the bot

---

lib/pangea/analytics_misc/level_up.dart

chore: hide level up details on production

---

lib/pages/chat/chat.dart

chore: don't show message overlay if not on chat page

---

lib/pages/chat/chat.dart
lib/pages/chat/events/message.dart
lib/pangea/common/widgets/pressable_button.dart
lib/pangea/toolbar/widgets/overlay_message.dart

chore: remove message bubble from emoji messages

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: enable chat downloads in DMs

---

lib/pangea/toolbar/widgets/select_mode_buttons.dart

fix: play audio from file on mobile

---

lib/pangea/constructs/construct_identifier.dart
lib/pangea/lemmas/lemma_emoji_row.dart

chore: when user sets lemma emoji, if analytics doesn't exist, make it

---

lib/pages/chat/chat.dart
lib/pages/chat/events/audio_player.dart
lib/pages/chat/events/message_content.dart
lib/pages/chat/events/video_player.dart
lib/pangea/toolbar/controllers/tts_controller.dart

chore: pause playing videos when user leaves chat page

---

lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart

chore: make lemma header text wrap

---

lib/widgets/adaptive_dialogs/user_dialog.dart
lib/widgets/member_actions_popup_menu_button.dart

chore: add user public profile info to user profile dialog

---

lib/pangea/toolbar/widgets/overlay_header.dart

Makes fluffychat Share button an option when selecting audio/image/file messages

Add share button selection option

---

lib/pages/chat/input_bar.dart

chore: update bot avatar in mention popup

---

lib/config/routes.dart
lib/pages/chat/chat.dart
lib/pages/chat_list/chat_list.dart
lib/pages/new_group/new_group.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/spaces/controllers/space_controller.dart
lib/pangea/spaces/utils/join_with_alias.dart
lib/pangea/spaces/utils/join_with_link.dart
lib/widgets/adaptive_dialogs/public_room_dialog.dart

chore: set active space via route instead of stream

---

lib/pages/chat/events/room_creation_state_event.dart

chore: fix tooltip being squished in room creation state event widget

---

.github/workflows/dart_format.yaml

chore: turn of dysfunctional dart auto-formatter gh action

---

lib/pages/chat_details/participant_list_item.dart
lib/pages/invitation_selection/invitation_selection_view.dart
lib/pangea/analytics_misc/level_display_name.dart

Gets rid of long id, moves level info to subtitle

Rearrange tile for less clutter

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/chat_settings/widgets/class_name_header.dart

- Fix Android centering issue 
- Make DM detail header match Fluffychat behavior ("Chat details", can't edit)

Details page header tweaks

---

assets/l10n/intl_en.arb
lib/pangea/analytics_details_popup/analytics_details_popup.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_view.dart
lib/pangea/analytics_downloads/analytics_dowload_dialog.dart
lib/pangea/analytics_downloads/analytics_download_button.dart
lib/pangea/analytics_downloads/analytics_summary_enum.dart
lib/pangea/analytics_downloads/analytics_summary_model.dart
lib/pangea/analytics_downloads/download_analytics_button.dart
lib/pangea/analytics_downloads/space_analytics_summary_enum.dart
lib/pangea/analytics_downloads/space_analytics_summary_model.dart
lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/analytics_misc/construct_type_enum.dart
lib/pangea/analytics_misc/construct_use_type_enum.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/chat_settings/widgets/download_space_analytics_button.dart
lib/pangea/spaces/widgets/download_space_analytics_dialog.dart

feat: personal analytics downloads

---

assets/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pages/invitation_selection/invitation_selection.dart
lib/pages/invitation_selection/invitation_selection_view.dart
lib/pages/new_group/new_group.dart
lib/pangea/chat_settings/widgets/class_invitation_buttons.dart
lib/pangea/chat_settings/widgets/space_invite_buttons.dart
lib/pangea/extensions/room_space_settings_extension.dart

refactor: new invite page design

---

lib/pangea/analytics_downloads/analytics_dowload_dialog.dart

chore: fix null check error in analytics download dialog

---

lib/config/routes.dart
lib/pages/chat_list/chat_list.dart
lib/pages/invitation_selection/invitation_selection_view.dart

chore: remove backdoor to space page on mobile

---

lib/pangea/analytics_summary/progress_bar/animated_level_dart.dart

chore: add minimum width to level progress bar

---

lib/pangea/common/widgets/customized_svg.dart

chore: refresh SVG cache once a day

---

lib/pangea/analytics_misc/level_display_name.dart
lib/widgets/adaptive_dialogs/user_dialog.dart
lib/widgets/member_actions_popup_menu_button.dart

chore: fix bot face in user popup

---

assets/l10n/intl_en.arb
lib/pages/chat_permissions_settings/chat_permissions_settings_view.dart
lib/pages/chat_permissions_settings/permission_list_tile.dart
lib/pages/new_group/new_group.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: show space permissions

---

lib/pages/chat/events/video_player.dart

chore: try to enable video player on web on windows machine

---

lib/config/routes.dart
lib/pages/chat/chat_view.dart
lib/pages/chat_list/chat_list.dart
lib/pages/chat_list/chat_list_body.dart
lib/pages/chat_list/space_view.dart
lib/pages/new_group/new_group.dart
lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/chat/constants/default_power_level.dart
lib/pangea/common/controllers/pangea_controller.dart
lib/pangea/extensions/room_children_and_parents_extension.dart
lib/pangea/public_spaces/public_space_card.dart
lib/pangea/spaces/constants/space_constants.dart
lib/pangea/spaces/controllers/space_controller.dart
lib/pangea/spaces/utils/client_spaces_extension.dart
lib/pangea/user/client_extension.dart
lib/utils/client_manager.dart
lib/utils/url_launcher.dart
lib/widgets/adaptive_dialogs/public_room_dialog.dart

2742 bring back starter chats for top level spaces

---

.github/workflows/main_deploy.yaml

chore: test to fix upload of env overrides

---

.github/workflows/main_deploy.yaml
.github/workflows/manual.yml

Fix environment file

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: hide permissions tile for DMs

---

lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: move close button to the right in activity suggestion dialog

---

.github/workflows/main_deploy.yaml
lib/pangea/common/config/environment.dart

chore: fix env url

---

lib/config/app_config.dart

Makes AppConfig.hideRedactedEvents default to true

Hide redacted events by default

---

lib/pangea/toolbar/widgets/overlay_header.dart

chore: make overlay header scrollable

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/choreographer/widgets/it_bar.dart

- Adds gap between inline instruction and hint card
- Rounds top corners of IT bar

Adjust IT bar appearance

---

assets/l10n/intl_en.arb
lib/config/routes.dart
lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/activity_plan_card.dart
lib/pangea/activity_planner/activity_planner_builder.dart
lib/pangea/activity_planner/activity_planner_page.dart
lib/pangea/activity_planner/activity_planner_page_appbar.dart
lib/pangea/activity_planner/bookmarked_activity_list.dart
lib/pangea/activity_suggestions/activity_room_selection.dart
lib/pangea/activity_suggestions/activity_suggestion_carousel.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/activity_suggestions/suggestions_page.dart
lib/pangea/common/widgets/full_width_dialog.dart
lib/pangea/extensions/room_events_extension.dart
lib/pangea/public_spaces/public_spaces_area.dart

2765 direct users to add to chat with multiselect rather than create

---

lib/pages/new_group/new_group.dart
lib/pages/new_group/new_group_view.dart

- For space and chat creation, makes the criteria for rejecting a submission attempt and showing 'Please fill out' consistent

Cleaned up name submission criteria

---

lib/pages/chat/events/html_message.dart

chore: new logic for wrapping tokens in HTML messages

---

lib/pangea/activity_planner/activity_planner_builder.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: scroll activity dialog image with other content

---

lib/pangea/practice_activities/activity_type_enum.dart
lib/pangea/practice_activities/message_activity_request.dart
lib/pangea/practice_activities/practice_activity_model.dart
lib/pangea/practice_activities/practice_target.dart
pubspec.yaml

Merge prod into main

---

lib/pages/chat/events/reply_content.dart

For the user's own replies in dark mode, make the replied message's sender's name darker

Make replied message senders name readable on light background

---

lib/widgets/navigation_rail.dart

chore: wrap nav rail in material and safearea widgets

---

assets/l10n/intl_en.arb
lib/pangea/activity_suggestions/activity_suggestions_area.dart

chore: add timeout to activity search

---

lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

fix(word_zoom_widget): hide text.content.text if same as lemma.text

---

lib/pangea/spaces/constants/space_constants.dart
lib/pangea/spaces/utils/client_spaces_extension.dart

chore: add intro and accouncement chat icons

---

lib/pages/chat/events/html_message.dart

chore: fix widget span centering

---

lib/pangea/extensions/pangea_room_extension.dart
lib/pangea/extensions/room_events_extension.dart

chore: bookmark launched activities

---

assets/l10n/intl_en.arb

chore: fix typo in copy

---

assets/l10n/intl_en.arb
lib/pages/chat_permissions_settings/permission_list_tile.dart
lib/pangea/chat/constants/default_power_level.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: add permission to send activity events to newly created chats

---

ios/Runner.xcodeproj/project.pbxproj
lib/pangea/activity_suggestions/suggestions_page.dart

chore: scroll up on page after selecting search bar

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: auto-load all participants on mobile

---

lib/pages/chat_list/space_view.dart
lib/pages/chat_list/status_msg_list.dart
lib/pages/settings/settings.dart
lib/pages/settings/settings_view.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/spaces/widgets/leaderboard_participant_list.dart

2842 show participants in chat list

---

lib/pages/chat/events/html_message.dart
lib/pages/chat_list/chat_list_body.dart

chore: add missing bot avatar

---

lib/pages/chat/events/html_message.dart

chore: fix alignment of mentions in html messages

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: adjust some sizing in room details page

---

lib/pangea/chat/widgets/pangea_chat_input_row.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: use root navigator for popup menus

---

lib/pangea/find_your_people/find_your_people_view.dart

chore: add right side padding to find your people search bar

---

lib/pages/chat/chat.dart

chore: close emoji picker on chat tap without opening toolbar

---

lib/pages/chat_list/space_view.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/analytics_misc/client_analytics_extension.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/common/config/environment.dart
lib/pangea/toolbar/widgets/practice_activity/word_audio_button.dart

chore: some sentry fixes

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

Adds tooltips to room details buttons when in mini mode
- [ x ] Code formatting and import sorting has been done with `dart format lib/ test/` and `dart run import_sorter:main --no-comments`
- [ ] Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every release, …

Space details tooltips

---

lib/pangea/login/pages/user_settings.dart

fix: set user base language by user selection

---

lib/pangea/onboarding/onboarding.dart

chore: set invite step to complete if user has DM with non-bot user

---

pubspec.lock

build: update matrix SDK

---

lib/pages/chat/events/audio_player.dart

chore: reset audio when playing ends

---

lib/pages/chat/chat.dart

chore: forward display event when timeline is available

---

lib/pages/chat/events/audio_player.dart

chore: comment out external audio message player

---

lib/pages/chat/events/audio_player.dart
lib/pages/chat/events/reply_content.dart
lib/pages/chat/reply_display.dart

chore: fix audio time going to two lines when font size is large

---

lib/pangea/learning_settings/pages/settings_learning_view.dart
lib/pangea/learning_settings/widgets/p_language_dropdown.dart

- Removes possibility of duplicate language warning overflow
- Removes possibility of language tile overflow
- [ ] Android
- [ ] iOS

Fix language overflow

---

lib/pangea/lemmas/lemma_reaction_picker.dart

chore: update emojis when switching between different tokens

---

lib/l10n/intl_en.arb
lib/pangea/toolbar/widgets/overlay_message.dart

chore: update transcription error message

---

lib/pangea/public_spaces/public_room_bottom_sheet.dart

Don't use public space default image/description for joining chats in space

---

lib/pangea/toolbar/widgets/select_mode_buttons.dart

Use translate tooltip for speech translation button

---

lib/pangea/phonetic_transcription/phonetic_transcription_widget.dart
lib/pangea/toolbar/widgets/overlay_message.dart

chore: add phonetic transcription to audio message toolbar

---

lib/pages/chat_members/chat_members.dart

chore: prevent getting stuck in chat members with no filters

---

lib/pangea/practice_activities/activity_type_enum.dart
lib/pangea/practice_activities/practice_selection.dart

chore: don't show match activities for single-word messages

---

lib/pangea/activities/activity_duration_popup.dart

chore: fix can't edit duration on firefox/safari

---

lib/pangea/lemmas/construct_xp_widget.dart

chore: in lemma constructs button, don't execute onTap if no points

---

lib/pages/chat/events/html_message.dart

chore: fix mention font size

---

lib/pages/chat_list/chat_list.dart

Limit size of chat selection popup title 
- [ ] Android

Chat select overflow fix

---

lib/pangea/onboarding/onboarding_complete.dart

Makes onboarding text smaller so that it doesn't overlap with image
- [ ] Android
- [ ] iOS

chore: make onboarding text smaller

---

lib/pages/chat/events/html_message.dart

chore: exclude reply content from HTML token search

---

lib/pages/chat/chat.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/overlay_header.dart

chore: deselect events in message overlay dispose function

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart

chore: make room details buttons expand to fill available space

---

lib/pages/chat/events/html_message.dart

chore: use node.text instead of node.innerhtml

---

lib/pangea/toolbar/widgets/message_audio_card.dart

chore: fix audio player unique ID mixup

---

lib/pages/chat/events/message_reactions.dart

chore: fix emoji reaction centering on iOS

---

lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/spaces/utils/load_participants_util.dart

chore: make non-joined room members less opaque in room details view

---

lib/pages/chat/events/audio_player.dart
lib/pages/chat/events/message_content.dart

chore: don't select audio message on click play button

---

lib/pangea/analytics_details_popup/vocab_analytics_details_view.dart
lib/pangea/choreographer/controllers/igc_controller.dart
lib/pangea/events/event_wrappers/pangea_message_event.dart
lib/pangea/lemmas/lemma_reaction_picker.dart
lib/pangea/message_token_text/token_position_model.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/overlay_message.dart
lib/pangea/toolbar/widgets/stt_transcript_tokens.dart

feat: make tokens in STT transcript clickable

---

lib/pangea/common/utils/overlay.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart

chore: increase background blur when toolbar is open

---

lib/pages/chat/chat.dart
lib/pages/chat/events/message_content.dart
lib/pangea/toolbar/widgets/select_mode_buttons.dart

chore: fix audio ID issue

---

lib/pages/chat_list/chat_list.dart
lib/pangea/activity_planner/activity_planner_page_appbar.dart

chore: center activity page title

---

lib/pages/chat/events/audio_player.dart

chore: replace mic icon with 1x default playback speed icon

---

lib/widgets/member_actions_popup_menu_button.dart

fix: Ban button displayed for already banned users

---

lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: fix overflow in word card text

---

lib/pangea/phonetic_transcription/phonetic_transcription_widget.dart

chore: update phonetic transcription when text changes

---

lib/pages/chat/chat_event_list.dart
lib/pages/chat/events/message.dart
lib/pangea/activities/activity_state_event.dart
lib/pangea/events/constants/pangea_event_types.dart
lib/utils/matrix_sdk_extensions/filtered_timeline_extension.dart

Reverts pangeachat/client#3206

Revert "chore: add fake event to show when activity ended"

---

lib/pangea/chat_settings/widgets/delete_space_dialog.dart

chore: don't expand delete space dialog if empty

---

lib/pangea/learning_settings/pages/settings_learning.dart

chore: remove wait for sync when updating learning settings

---

lib/pangea/subscription/controllers/subscription_controller.dart

chore: if user is in trial window, always treat them as subscribed

---

lib/pages/chat_list/chat_list.dart
lib/pangea/chat_list/utils/chat_list_handle_space_tap.dart
lib/widgets/navigation_rail.dart

chore: on click space in nav rail, if invited, show invite popup

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart

If there are no activities after loading finishes, display error message

---

lib/pangea/learning_settings/pages/settings_learning.dart

chore: wait for language change updates in sync

---

lib/pages/chat/events/html_message.dart

chore: small token order fix

---

lib/pages/chat/chat.dart

chore: fix autoplay bot messages on android

---

lib/pages/chat_search/chat_search_message_tab.dart

Limit space taken up by chat search result's sender name

---

lib/config/routes.dart
lib/pangea/analytics_details_popup/analytics_details_popup.dart
lib/pangea/analytics_page/analytics_page.dart
lib/pangea/analytics_page/analytics_page_view.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/analytics_summary/progress_indicators_enum.dart
lib/pangea/chat/utils/unlocked_morphs_snackbar.dart
lib/pangea/choreographer/widgets/igc/message_analytics_feedback.dart
lib/pangea/toolbar/widgets/word_zoom/morphological_list_item.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: redirect to analytics page instead of opening analytics popup

---

lib/pages/chat_search/chat_search_message_tab.dart

chore: filter out non-visible events from search results

---

lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

Uses lowercase versions of lemma/form when comparing

---

lib/pangea/analytics_details_popup/morph_analytics_list_view.dart

- Change gradient direction, so lightest background is on icon side
- give icon background circle to prevent blending into colored gradient background
- [ ] Android
- …

Make grammar category buttons more readable

---

lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

chore: make toolbar key constant to prevent rebuilds

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart

chore: don't call lemma_defintion for all tokens when opening toolbar

---

lib/config/routes.dart
lib/l10n/intl_en.arb
lib/pages/invitation_selection/invitation_selection.dart
lib/pages/invitation_selection/invitation_selection_view.dart
lib/pangea/chat_settings/pages/pangea_chat_details.dart
lib/pangea/chat_settings/pages/pangea_invitation_selection.dart
lib/pangea/chat_settings/pages/pangea_invitation_selection_view.dart

3028 easier to invite users to a chat

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart

chore: reenable translation button for audio messages

---

lib/pangea/analytics_details_popup/analytics_details_popup.dart
lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_view.dart
lib/pangea/analytics_page/analytics_page_view.dart

chore: update analytics page spacing for mobile

---

lib/pangea/toolbar/controllers/tts_controller.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Switches windows from TextToSpeech for TTS to FlutterTts so that it can time and switch between audio/pause icons correctly
- [ ] Android
- [ ] iOS

3385 speaker button switches back from pause button too quickly when clicked

---

lib/config/routes.dart
lib/pages/login/login.dart
lib/pages/login/login_view.dart
lib/pangea/login/pages/pangea_login_view.dart

chore: load client within login page instead of passing to route

---

lib/pages/chat/events/message.dart

Revert pangea code that prevents reaction wrapping

---

lib/widgets/member_actions_popup_menu_button.dart

Close profile card when click off

---

lib/pangea/login/utils/sso_login_action.dart

chore: fix sso redirect URL

---

lib/pangea/phonetic_transcription/phonetic_transcription_widget.dart

Hide phonetics spacing if not showing icon after

---

lib/pangea/common/widgets/error_indicator.dart

Fix activity timeout overflow

---

lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

Unselect word on close word zoom card

---

lib/pangea/activity_suggestions/activity_suggestions_area.dart

Hide 'Try again' button on activity timeout

---

lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/suggestion_form_field.dart

(old PR [here](https://github.com/pangeachat/client/pull/3460))
I haven't tested this yet. I'll edit it once I do.
- [ ] Android
- [ ] iOS
- [ ] …

Add activity generator maxLength via SuggestionFormField parameter

---

lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/constructs/construct_repo.dart

chore: update construct level summary request

---

lib/widgets/member_actions_popup_menu_button.dart

Fix profile popup positioning

---

lib/pages/chat/events/html_message.dart

Don't allow selection of lemmas containing numerals

---

lib/pangea/analytics_downloads/analytics_dowload_dialog.dart

chore: fix analytics CSV download

---

lib/pages/new_group/new_group.dart
lib/pangea/chat_settings/pages/pangea_invitation_selection.dart

When a parent is added to new chat, load before opening invite page

---

lib/pangea/activity_planner/activity_planner_builder.dart
lib/pangea/activity_suggestions/activity_suggestion_dialog.dart

chore: display loading during image upload

---

lib/pages/chat/reply_display.dart

Make editing text flexible

---

lib/pangea/events/event_wrappers/pangea_message_event.dart
lib/pangea/extensions/room_events_extension.dart
lib/pangea/toolbar/widgets/select_mode_buttons.dart

chore: use more specific substring to check for temporary event IDs

---

lib/pangea/analytics_page/analytics_page_view.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart

On the level analytics page level bar:
- Don't change background on hover
- Don't change cursor appearance on hover
- Don't do anything on click
- [ ] Android
- [ ] iOS
- [ ] …

If clicking level bar does nothing, make it act unselectable

---

lib/pangea/spaces/controllers/space_controller.dart

Use correct route when join class by link

---

lib/pangea/toolbar/widgets/message_selection_positioner.dart

chore: some fixes for overlay positioning

---

lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/over_message_overlay.dart
lib/pangea/toolbar/widgets/overlay_center_content.dart

reaction placement

---

lib/pages/chat/events/message.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart
lib/pangea/toolbar/widgets/overlay_center_content.dart

3431 accommodate wrapped reactions in message selection overlay

---

lib/pages/chat/events/message_download_content.dart

Add flexible to file messages to prevent long name overflow

---

lib/main.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/analytics_misc/put_analytics_controller.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart
lib/pangea/choreographer/controllers/choreographer.dart
lib/pangea/common/controllers/pangea_controller.dart
lib/pangea/learning_settings/utils/locale_provider.dart
lib/pangea/lemmas/construct_xp_widget.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/user/controllers/user_controller.dart
lib/widgets/fluffy_chat_app.dart
lib/widgets/matrix.dart

feat: set app language to user's L1

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

fix: update mismatched keys to show XP animation on collection

---

lib/pages/chat/events/html_message.dart

chore: don't allow selection of symbol tokens

---

lib/pages/chat/chat.dart

Doesn't do much since redaction messages aren't currently shown, but will limit them to a reasonable length if they're ever added back
- [ ] Android
- [ ] iOS

fix: limit redaction message

---

lib/pages/chat/input_bar.dart
lib/pangea/extensions/room_events_extension.dart

chore: disable command parsing

---

lib/pages/chat/chat.dart
lib/pages/chat/events/message.dart

Unhighlights message when pin is removed
- [ ] Android
- [ ] iOS

3607 pinned message highlight persists after unpinning

---

lib/pangea/activity_planner/activity_room_extension.dart

chore: exclude bot when checking if activity is finished

---

lib/pangea/chat/utils/unlocked_morphs_snackbar.dart

Decrease grammar popup text size in column mode

---

lib/pages/chat_list/chat_list.dart
lib/pangea/activity_sessions/activity_room_extension.dart
lib/pangea/choreographer/controllers/choreographer.dart

chore: always reset lastChecked string in choreo on changed listener

---

lib/pangea/analytics_misc/get_analytics_controller.dart

Change grammar threshold from 25 to 30

---

lib/pangea/activity_sessions/activity_participant_indicator.dart

Use different name color for dark mode

---

lib/pangea/activity_sessions/activity_room_extension.dart
lib/pangea/activity_sessions/activity_state_event.dart
lib/pangea/activity_sessions/activity_status_message.dart
lib/pangea/activity_sessions/activity_unfinished_status_message.dart

Conditionally render participants

---

lib/pangea/activity_generator/activity_generator.dart
lib/pangea/activity_generator/activity_generator_view.dart
lib/pangea/activity_planner/suggestion_form_field.dart

Make objective/topic/mode nullable lists instead of async

---

lib/pangea/activity_generator/activity_generator.dart
lib/pangea/activity_planner/activity_plan_model.dart
lib/pangea/activity_planner/activity_planner_builder.dart
lib/pangea/common/constants/model_keys.dart

chore: use activity IDs from the choreo response

---

lib/pangea/activity_planner/activity_plan_model.dart

chore: fallback to old activity IDs

---

lib/pages/chat/events/html_message.dart

chore: fix substring index issue with emoji characters

---

lib/pangea/activity_sessions/activity_status_message.dart
lib/pangea/activity_sessions/load_activity_summary_widget.dart
lib/pangea/activity_summary/activity_summary_model.dart

fix: improve logic for when to request missing activity summary

---

lib/pangea/chat_settings/pages/pangea_invitation_selection_view.dart

chore: add power level labels in invite page

---

lib/pages/chat/events/message.dart
lib/pangea/activity_sessions/activity_role_model.dart
lib/pangea/activity_sessions/activity_roles_event.dart
lib/utils/matrix_sdk_extensions/filtered_timeline_extension.dart

chore: display activity role state events

---

lib/pangea/activity_sessions/load_activity_summary_widget.dart

chore: don't auto-request activity summary if last request caused error

---

lib/l10n/intl_en.arb
lib/pangea/activity_suggestions/activity_plan_search_repo.dart
lib/pangea/activity_suggestions/activity_search_enum.dart
lib/pangea/activity_suggestions/activity_suggestions_area.dart
lib/pangea/common/network/requests.dart

Use status codes to decide activity search behavior

---

lib/l10n/intl_en.arb
lib/pangea/space_analytics/space_analytics_view.dart

chore: fix overflow in space analytics page

---

lib/pangea/analytics_downloads/space_analytics_summary_model.dart
lib/pangea/analytics_misc/construct_list_model.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/analytics_misc/level_up/level_up_manager.dart
lib/pangea/analytics_summary/learning_progress_indicators.dart

fix: use unique construct IDs for calculating aggregate analytics data

---

lib/pangea/space_analytics/space_analytics_view.dart

Fix position/width of language dropdown

---

lib/l10n/intl_en.arb
lib/pangea/space_analytics/space_analytics_download_enum.dart
lib/pangea/space_analytics/space_analytics_view.dart

chore: tweaks to styling of not-available space analytics table rows

---

lib/pangea/space_analytics/space_analytics.dart

chore: load participants on init space analytics page

---

lib/pages/chat/chat.dart
lib/pages/chat_details/chat_details.dart
lib/pages/chat_list/space_view.dart
lib/pangea/spaces/utils/load_participants_util.dart
lib/utils/client_manager.dart

fix: load full participant list when needed

---

lib/pangea/space_analytics/space_analytics_view.dart

Only show space analytics download button on web

---

lib/l10n/intl_en.arb
lib/pangea/space_analytics/space_analytics_view.dart

- Removes duplicate '"noDataFound": "No data found",' entry
- Use language code instead of full language name on language selection button
- Makes request button wrap if needed
- Remove padding around request button  if there is no outline behind it (when status == RequestStatus.unavailable)
- [ ] Every new feature in the app or …

Space analytics overflow fixes

---

lib/pangea/space_analytics/space_analytics_view.dart

Center space analytics title for android

---

lib/pangea/space_analytics/space_analytics_requested_dialog.dart
lib/pangea/space_analytics/space_analytics_view.dart

- [ ] Android
- [ ] iOS
- [ ] Desktop …

add close button to analytics requested popup

---

lib/pangea/practice_activities/emoji_activity_generator.dart
lib/pangea/practice_activities/practice_match.dart
lib/pangea/toolbar/widgets/message_selection_positioner.dart

fix: pick another emoji if duplicate emojis in activities

---

lib/l10n/intl_en.arb
lib/pangea/chat_settings/pages/space_details_content.dart
lib/pangea/course_chats/course_chats_view.dart

chore: padding updates to course chats list

---

lib/pangea/message_token_text/message_token_button.dart
lib/pangea/practice_activities/emoji_activity_generator.dart

fix: only pass one emoji match option per token in emoji match activity

---

lib/pangea/public_spaces/public_room_bottom_sheet.dart

chore: remove share link button in space popup

---

lib/widgets/navigation_rail.dart

fix: only could chats within space parents in all chats unread bubble

---

lib/l10n/intl_en.arb
lib/pangea/activity_sessions/activity_session_start/activity_session_start_page.dart

chore: update ping notification content

---

lib/pangea/activity_sessions/activity_session_start/activity_session_start_page.dart
lib/pangea/activity_sessions/activity_session_start/activity_sessions_start_view.dart

Don't show play with bots button if bot has already been invited

---

lib/pangea/activity_sessions/activity_room_extension.dart
lib/pangea/activity_sessions/activity_session_analytics_repo.dart
lib/pangea/analytics_misc/get_analytics_controller.dart
lib/pangea/common/controllers/pangea_controller.dart
lib/pangea/extensions/room_events_extension.dart

feat: add local cache for activity session analytics

---

lib/pages/chat/chat_view.dart
lib/pages/chat_permissions_settings/chat_permissions_settings_view.dart
lib/pangea/activity_sessions/activity_room_extension.dart
lib/pangea/activity_sessions/activity_session_chat/activity_finished_status_message.dart
lib/pangea/chat/constants/default_power_level.dart

fix: in new courses, set course_user state event power level to 0

---

lib/l10n/intl_en.arb

fix: remove dollar sign from copy

---

lib/l10n/intl_en.arb
lib/pangea/analytics_misc/level_up/level_up_banner.dart

Level up popup tweaks

---

lib/pangea/activity_sessions/activity_session_chat/activity_role_tooltip.dart
lib/pangea/chat/widgets/chat_input_bar.dart

chore: hide activity role tooltip when it bar is open

---

lib/pangea/activity_sessions/activity_session_chat/activity_role_tooltip.dart

fix: fix null check error in activity role tooltip

---

lib/pages/chat/events/html_message.dart
lib/pangea/course_plans/course_plan_builder.dart
lib/pangea/message_token_text/tokens_util.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/stt_transcript_tokens.dart

feat: always show new tokens with green underlines

---

lib/pangea/toolbar/widgets/word_zoom/new_word_overlay.dart

chore: collection seed always fades up and out

---

lib/pages/chat_list/chat_list_item.dart
lib/pangea/course_chats/course_chats_view.dart
lib/pangea/course_creation/selected_course_page.dart
lib/pangea/course_plans/course_plan_room_extension.dart
lib/pangea/spaces/utils/client_spaces_extension.dart

3988 activitycourse tweaks

---

lib/pangea/activity_sessions/activity_participant_indicator.dart
lib/pangea/activity_sessions/activity_participant_list.dart
lib/pangea/activity_sessions/activity_user_summaries_widget.dart

chore: show user menu on click participant item

---

lib/pages/chat/chat.dart
lib/pages/chat/events/html_message.dart
lib/pangea/message_token_text/tokens_util.dart
lib/pangea/toolbar/widgets/message_selection_overlay.dart

fix: don't show green underlines on own messages

---

scripts/build-web.sh

fix: replace build-web script

---

lib/pangea/activity_sessions/activity_participant_indicator.dart

Add dark/light mode check for unassigned participant label color

---

lib/pangea/analytics_details_popup/morph_analytics_list_view.dart
lib/pangea/analytics_details_popup/vocab_analytics_list_view.dart

chore: move analytics tooltips inside scrollviews

---

lib/widgets/navigation_rail.dart

chore: update icon and border of find a course nav rail item

---

lib/l10n/intl_en.arb
lib/pangea/chat_settings/pages/edit_course.dart

chore: add hint text to text fields in course edit page

---

lib/l10n/intl_en.arb
lib/pangea/chat_settings/pages/edit_course.dart

chore: show snackbar on course edit save

---

lib/pangea/chat_settings/pages/edit_course.dart
lib/pangea/chat_settings/pages/space_details_content.dart

chore: disable save edits button if no changes in course edit page

---

lib/pages/chat/events/room_creation_state_event.dart

chore: don't animate in-chat tooltips

---

lib/config/routes.dart
lib/l10n/intl_en.arb
lib/pangea/course_creation/new_course_page.dart
lib/pangea/course_creation/new_course_view.dart
lib/pangea/course_creation/selected_course_page.dart
lib/pangea/course_creation/selected_course_view.dart
lib/pangea/course_plans/course_plan_room_extension.dart
lib/pangea/course_settings/course_settings.dart

feat: add ability to add course to existing space

---

lib/pangea/common/controllers/pangea_controller.dart

fix: don't attempt to load analytics until your is logged in

---

lib/config/routes.dart
lib/pages/chat/chat.dart
lib/pangea/activity_sessions/activity_participant_list.dart
lib/pangea/activity_sessions/activity_session_start/activity_session_start_page.dart
lib/pangea/activity_sessions/activity_session_start/activity_sessions_start_view.dart
lib/pangea/activity_sessions/activity_summary_widget.dart
lib/pangea/chat_settings/utils/room_summary_extension.dart
lib/pangea/course_chats/activity_template_chat_list_item.dart
lib/pangea/course_chats/course_chats_page.dart
lib/pangea/course_chats/course_chats_view.dart
lib/pangea/course_plans/activity_summaries_provider.dart
lib/pangea/course_plans/course_plan_room_extension.dart
lib/pangea/course_plans/course_user_event.dart
lib/pangea/course_settings/course_settings.dart

feat: integrate room preview endpoint

---

lib/pages/chat/events/message.dart

Remove gap above activity image in scroll view

---

lib/l10n/intl_en.arb
lib/pangea/activity_planner/activity_plan_model.dart
lib/pangea/activity_sessions/activity_session_chat/activity_stats_menu.dart
lib/pangea/course_plans/course_plan_builder.dart
lib/pangea/learning_settings/pages/settings_learning.dart
lib/pangea/learning_settings/pages/settings_learning_view.dart
lib/pangea/lemmas/lemma_reaction_picker.dart
lib/pangea/message_token_text/token_practice_button.dart
lib/pangea/toolbar/widgets/reading_assistance_content.dart
lib/pangea/toolbar/widgets/word_zoom/new_word_overlay.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart
lib/pangea/user/models/user_model.dart

4036 playtest 91825

---

lib/pages/new_group/new_group.dart
lib/pangea/course_creation/selected_course_page.dart
lib/pangea/course_plans/course_plan_room_extension.dart
lib/pangea/login/pages/user_settings.dart
lib/pangea/spaces/utils/client_spaces_extension.dart
lib/pangea/subscription/controllers/subscription_controller.dart
lib/pangea/toolbar/enums/message_mode_enum.dart
lib/pangea/toolbar/widgets/select_mode_buttons.dart
lib/widgets/avatar.dart

Playtest updates

---

lib/pangea/activity_planner/activity_plan_model.dart
lib/pangea/activity_sessions/activity_summary_widget.dart
pubspec.lock
pubspec.yaml

chore: render activity instruction markdown

---

lib/pangea/choreographer/widgets/it_shimmer.dart

chore: disable hover effect on loading span card icons

---

lib/pangea/activity_sessions/activity_session_start/activity_session_start_page.dart
lib/pangea/activity_sessions/activity_session_start/activity_sessions_start_view.dart

fix: fix needed participants copy

---

lib/pangea/chat_settings/pages/edit_course.dart

fix: don't reset edits using the room's title and description

---

android/app/build.gradle.kts
lib/pages/chat/events/html_message.dart
lib/pangea/toolbar/widgets/over_message_overlay.dart
lib/pangea/toolbar/widgets/select_mode_buttons.dart

fix: fix toolbar buttons on mobile

---

lib/pangea/message_token_text/token_practice_button.dart

chore: add gold shimmer to active token practice buttons

---

lib/pangea/toolbar/reading_assistance_input_row/message_morph_choice.dart

chore: remove unnecessary spacing

---

lib/pangea/course_creation/new_course_page.dart

chore: add no courses found indicator

---

lib/pangea/login/pages/login_options_view.dart
lib/pangea/login/pages/signup_view.dart

chore: make terms and conditions links work

---

lib/config/routes.dart

fix: always set vocab as default tab in analytics page

---

lib/pages/chat_access_settings/chat_access_settings_page.dart
lib/pages/chat_encryption_settings/chat_encryption_settings_view.dart
lib/pangea/instructions/instructions_toggle.dart
lib/pangea/learning_settings/pages/settings_learning_view.dart
lib/pangea/learning_settings/widgets/p_settings_switch_list_tile.dart
lib/pangea/login/widgets/app_config_dialog.dart

build: fix lints for new flutter version

---

lib/pangea/toolbar/utils/token_rendering_util.dart

Make underlines translucent so lower parts of letters can be seen

---

lib/pangea/toolbar/widgets/message_selection_overlay.dart
lib/pangea/toolbar/widgets/reading_assistance_content.dart
lib/pangea/toolbar/widgets/word_zoom/new_word_overlay.dart
lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart

fix: don't dispose new word overlay animation early

---

lib/pangea/course_creation/course_search_provider.dart
lib/pangea/course_plans/course_plans_repo.dart
lib/pangea/login/pages/new_trip_page.dart
lib/pangea/payload_client/payload_client.dart

chore: on course search, always load course IDs from server

---

lib/config/routes.dart

fix: fix double analytics view in two column mode

---

lib/pangea/chat/widgets/chat_input_bar.dart

chore: give activity goal tooltip max width

---

lib/pangea/message_token_text/tokens_util.dart

4181 japanese words grouped when should be separate

---

lib/pangea/choreographer/controllers/it_controller.dart

chore: don't show choreo error on timeout after canceling translation

---

lib/pangea/course_creation/course_invite_page.dart
lib/pangea/login/pages/language_selection_page.dart
lib/pangea/login/pages/login_options_view.dart
lib/pangea/login/pages/login_or_signup_view.dart
lib/pangea/login/pages/pangea_login_view.dart
lib/pangea/login/pages/plan_trip_page.dart
lib/pangea/login/pages/private_trip_page.dart
lib/pangea/login/pages/signup_view.dart
lib/pangea/login/pages/signup_with_email_view.dart
lib/pangea/login/widgets/p_sso_button.dart

chore: re-style onboarding buttons

---

lib/pages/chat/chat.dart
lib/pages/chat/chat_view.dart
lib/pangea/activity_sessions/activity_room_extension.dart
lib/pangea/activity_sessions/activity_session_chat/activity_finished_status_message.dart
lib/pangea/activity_sessions/activity_session_chat/activity_stats_menu.dart
lib/pangea/activity_sessions/activity_session_start/activity_session_start_page.dart
lib/pangea/chat_list/utils/get_chat_list_item_subtitle.dart
lib/pangea/chat_settings/widgets/chat_context_menu_action.dart
lib/pangea/course_plans/course_plan_room_extension.dart
lib/pangea/extensions/room_information_extension.dart

4197 course ping should be disabled if there are no other course participants

---

lib/l10n/intl_en.arb
lib/pages/chat/chat.dart
lib/pangea/choreographer/controllers/choreographer.dart
lib/pangea/choreographer/utils/language_mismatch_repo.dart
lib/pangea/choreographer/widgets/igc/language_mismatch_popup.dart
lib/pangea/choreographer/widgets/start_igc_button.dart
lib/pangea/common/controllers/pangea_controller.dart

feat: show warning popup on l2/activity language mixup

---

lib/pages/chat/chat_view.dart

Adjust unread badge height to compensate for activity header height

---

lib/pangea/activity_sessions/activity_session_chat/activity_finished_status_message.dart

fix: hide activity finished status message for archived activities

---

lib/pangea/spaces/controllers/space_code_controller.dart

fix: fix join with code redirect for non-spaces

---

lib/pangea/user/utils/p_login.dart

fix: fix onboarding redirect on login

---

lib/pangea/chat_settings/pages/room_participants_widget.dart

Remove invite option from participants widget in DM
