lib/pangea/widgets/user_settings/p_language_dropdown.dart
Trello ticket: https://trello.com/c/vWHHqgww
=> Sort English and Spanish to the top of the language list

lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/login/login_view.dart, lib/pangea/pages/sign_up/signup_view.dart, lib/pangea/widgets/signup/signup_buttons.dart, lib/pangea/widgets/signup/tos_checkbox.dart
Trello ticket: https://trello.com/c/2aIUOjtT
=> changed color of login/signup error message to makke them more visible

lib/pangea/widgets/class/add_space_toggles.dart
Trello ticket: https://trello.com/c/rCRRsmBE
=> updates to UI of add to space toggles, makes all class options visible without scrolling

lib/pages/chat_details/chat_details_view.dart
Trello ticket: https://trello.com/c/evrY8agb
=> Add un/lock icon as leading on lock toggle

lib/config/routes.dart, lib/pages/chat_list/chat_list_body.dart, lib/pages/chat_list/start_chat_fab.dart, lib/pangea/controllers/subscription_controller.dart, lib/pangea/extensions/pangea_room_extension.dart, lib/pangea/models/it_response_model.dart, lib/widgets/matrix.dart
Fixes for a variety of errors caught in sentry
=> Sentry Fixes

lib/pages/chat/events/message_content.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_translation_card.dart, lib/pangea/widgets/igc/pangea_rich_text.dart
- Show the active toolbar button in a different color
- Add space between toolbar and overlay message
- If there is selected text, show the translation of the selected text (not the whole message) after pressing the translate button
- Disable text selection if message is not highlighted
=> Show translation of selected text

assets/l10n/intl_en.arb, assets/l10n/intl_es.arb, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_unsubscribed_card.dart, lib/pangea/widgets/igc/paywall_card.dart
- In subscription popup, if user is qualified for free trial, have button in popup for activate trial
- Added tooltips to toolbar buttons
=> Toolbar Tooltips + Free Trial Buttons

lib/pages/chat/events/audio_player.dart, lib/pangea/models/pangea_message_event.dart, lib/pangea/widgets/chat/message_audio_card.dart, needed-translations.txt
- Decoupling the playing of text-to-speech audio from the sending of audio events
=> Decouple Audio

lib/pangea/extensions/client_extension.dart
Checks if teacher is user before adding to invite list
=> Checks if teacher is user before adding to invite list

assets/l10n/intl_en.arb, assets/l10n/intl_es.arb, lib/config/app_config.dart, lib/pangea/matrix_event_wrappers/pangea_message_event.dart, lib/pangea/models/speech_to_text_models.dart, lib/pangea/widgets/chat/message_speech_to_text_card.dart, needed-translations.txt
@ggurdin please review and add when ready! Want this for next release.
=> adding words per minute to speech to text feedback

assets/l10n/intl_en.arb, lib/pages/chat_list/client_chooser_button.dart, lib/pages/settings/settings_view.dart
Changes Learning Settings icon, changes name to 'My Learning Settings', and moves button from Settings to Main Menu
=> Adjusted learning settings

lib/pages/chat/events/message.dart
Checks that message is not redacted before opening toolbar
=> Checks that message is not redacted before opening toolbar

lib/pangea/pages/settings_learning/settings_learning_view.dart
Changed the default value of the autoplay option in My Learning Settings to false
=> Change default value of autoplay option to false

lib/widgets/chat_settings_popup_menu.dart
Updated the My Learning Settings icon in chat settings menu to the icon used in the main menu
=> Updated My Learning Settings icon in chat settings menu

lib/pangea/utils/get_chat_list_item_subtitle.dart
Fixed bug where redacted messages sometimes showed in chat subtitle
=> Fixed bug where redacted messages sometimes showed in chat subtitle

lib/pages/new_group/new_group_view.dart, lib/pages/new_space/new_space_view.dart, lib/pages/settings/settings.dart, lib/pangea/utils/set_class_name.dart
Sets a maximum length on display, chat, and class names.
=> Limit name length

lib/pages/archive/archive.dart, lib/pages/chat/chat_view.dart, lib/widgets/chat_settings_popup_menu.dart
Keeps archive from showing archived classes and analytics rooms
=> Archive list only shows chats

lib/pages/chat_list/start_chat_fab.dart, lib/pangea/extensions/pangea_room_extension.dart, lib/pangea/widgets/class/add_space_toggles.dart
Prevent those who are not admins of a room from editing what classes the room is a member of
=> Only admins toggle spaces

lib/pangea/pages/settings_learning/settings_learning.dart, lib/pangea/pages/settings_learning/settings_learning_view.dart, lib/pangea/widgets/user_settings/language_tile.dart, lib/pangea/widgets/user_settings/p_language_dialog.dart
Refreshes the page after user changes languages in Learning Settings.
=> Updates learning settings

lib/pages/homeserver_picker/homeserver_picker.dart, lib/pages/homeserver_picker/homeserver_picker_view.dart, lib/pages/login/login.dart
When a user logs in, the loading state remains until the main page is shown.
=> Shows loading screen after login

lib/pangea/models/constructs_analytics_model.dart, lib/pangea/models/headwords.dart
Hey Gabby, simple PR from my changes the other day when we were talking. Please check quickly then merge.
=> Analytics-notes

lib/pangea/choreographer/controllers/igc_controller.dart
Keep toolbar open when user clicks on newly sent message
=> Stop toolbar closing

lib/pangea/utils/set_class_topic.dart
=> Allow multiline topic input

lib/pages/invitation_selection/invitation_selection.dart, lib/pangea/utils/chat_list_handle_space_tap.dart
- Invitations to a class also sent invitations to subchats in the class. This caused some problems when reinviting teachers.
- Exchange invites redirected invited teachers to a page that never loaded.
=> Removed code that was messing with invites

assets/l10n/intl_en.arb, assets/l10n/intl_es.arb
Changes DM category to 'Direct chats' when viewed in analytics
=> Shorten name of DM analytics category

lib/pangea/models/span_data.dart, lib/pangea/widgets/igc/span_card.dart
When a user selects a span card choice, then closes and reopens the span card, the option will stay selected.
=> Save span card selection

lib/pages/chat_list/chat_list.dart
Chat list order is reverted to how Fluffychat does it
=> Remove sorting

lib/pages/chat_list/client_chooser_button.dart
Checks whether the user is in any visible chats before enabling My Analytics button
=> Better filter for my analytics button

lib/pages/chat_list/client_chooser_button.dart
Remove Find Conversation Partner button from main menu
=> Hide find convo partner

lib/pages/login/login_view.dart, lib/pages/new_space/new_space.dart
When a space is created as a child of another space, a welcome chat is not generated
=> No subspace welcome chat

lib/pages/chat_details/chat_details_view.dart, lib/pangea/extensions/pangea_room_extension/children_and_parents_extension.dart, lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart
In a subspace's Chat Details view, does not show the Add Students option
=> Remove button for subspaces

lib/pages/new_space/new_space.dart
When creating a new space, changes to the avatar remain after creation
=> Save new space avatar

assets/l10n/intl_en.arb, lib/pangea/utils/error_handler.dart
Adds specialized error message when speech to text fails
=> Adds speech to text error

lib/pages/chat_list/chat_list.dart, lib/pangea/extensions/pangea_room_extension/children_and_parents_extension.dart, lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart, lib/pangea/extensions/pangea_room_extension/room_analytics_extension.dart, lib/pangea/extensions/pangea_room_extension/user_permissions_extension.dart, lib/pangea/widgets/class/add_space_toggles.dart
Students in a space can create subchats or subspaces, or add them to the space
=> Students can add subrooms

lib/pages/chat/events/video_player.dart, lib/utils/localized_exception_extension.dart, lib/utils/matrix_sdk_extensions/matrix_locals.dart, pubspec.lock, pubspec.yaml
- address breaking changes of newer versions of matrix sdk:
https://github.com/pangeachat/matrix-dart-sdk/commit/6976c426a9f2e03d268788c26ebe6e28b4f161f2
=> integrate forked matrix sdk

lib/pages/chat/input_bar.dart, lib/pangea/widgets/chat/input_bar_wrapper.dart, lib/pangea/widgets/igc/pangea_text_controller.dart
When the user is typing a message in a chat, the text will turn red when they hit the character limit.
=> Red text on max length

lib/pangea/controllers/permissions_controller.dart, lib/pangea/extensions/pangea_room_extension/room_analytics_extension.dart
Doesn't use space permissions, since those can't be edited. Assumes most lenient permissions (allowed/student choice)
=> Lenient permissions

lib/pages/chat/events/message_content.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/overlay_message.dart
When a long message toolbar is opened, the overlay is shortened so the toolbar remains full size.
=> Shorten overlay instead of toolbar

lib/pages/chat/chat.dart
Silences web focus Sentry error
=> Silence web focus

lib/pangea/pages/analytics/analytics_view_button.dart, lib/pangea/pages/analytics/time_span_menu_button.dart
Makes analytics buttons flexible, so the text wraps instead of pushing the language button off the side of the screen.
=> Fix analytics overflow

lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/space_view.dart
=> Auto suggest 

lib/pangea/enum/message_mode_enum.dart
Enables activity tab on audio toolbar
=> Enables activity tab on audio toolbar

lib/pages/chat_details/chat_details_view.dart
Hero was causing weird visual glitch when navigating to chat details page. It is no longer doing that.
=> Deheroify avatar

lib/pages/chat/chat_view.dart
Fixes input bar blocking most recent message
=> Input bar spacing

lib/pangea/widgets/chat/message_toolbar.dart
Makes the entire width of toolbar scrollable (see attached issue)
=> Sets minimum width for toolbar content

lib/pages/chat/chat.dart
When the user clicks on the reply part of a message, the chat scrollss to the correct message
=> Fix reply scrolling

assets/l10n/intl_en.arb
Remove outdated reference to space languages
=> Update learning settings description

lib/pangea/choreographer/widgets/has_error_button.dart
Removes unecessary padding on choreographer error button
=> Remove error button padding

lib/pages/chat/event_info_dialog.dart, lib/pages/chat/events/message.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat/events/reply_content.dart, lib/pages/chat/seen_by_row.dart, lib/pages/chat/typing_indicators.dart, lib/pages/chat_details/participant_list_item.dart, lib/pages/chat_list/chat_list_item.dart, lib/pages/chat_search/chat_search_message_tab.dart, lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart, lib/utils/matrix_sdk_extensions/matrix_locals.dart, lib/utils/room_status_extension.dart
This reverts commit a36c52ff8703255335e6002c5a50a1ba32c771fe.
=> Revert "don't show user avatars or display names in chats"

lib/pages/chat/reactions_picker.dart
=> Add scene emoji reactions

lib/pages/chat/reactions_picker.dart
Adds heart emoji to game reaction picker
=> Add heart emoji

lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pangea/extensions/sync_update_extension.dart, lib/pangea/pages/games/story_game/round_model.dart
=> Revert "moved timer sync logic to seperate function, don't hide bot messages …"

lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart, lib/pangea/constants/model_keys.dart, lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart, lib/pangea/models/games/game_state_model.dart, lib/pangea/widgets/chat/game_state_view.dart, pubspec.lock, pubspec.yaml
Reverts pangeachat/client#659
Checking if this caused staging to crash
=> Revert "commented out references to judging mode"

lib/config/app_config.dart, lib/pangea/widgets/chat/message_toolbar.dart
=> fixed height of toolbar

pubspec.yaml
=> bumped version number

.github/workflows/release.yaml
=> bump version of deprecated package

assets/l10n/intl_en.arb, lib/pages/new_group/new_group.dart, lib/pangea/constants/bot_mode.dart, lib/pangea/models/bot_options_model.dart, lib/pangea/widgets/conversation_bot/conversation_bot_mode_dynamic_zone.dart, lib/pangea/widgets/conversation_bot/conversation_bot_mode_select.dart, lib/pangea/widgets/conversation_bot/conversation_bot_settings.dart, lib/pangea/widgets/conversation_bot/conversation_bot_settings_form.dart, pubspec.lock
- fix bug that kicks the bot if user confirm changes
- remove text adventure
- refactor bot mode into constants
=> fix bot dialog confirm kicks the bot undesirably

lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart, lib/pangea/widgets/chat/overlay_message.dart
=> Message overlay positioning

lib/pages/chat/chat_view.dart, lib/pangea/widgets/chat/chat_view_background.dart
=> blur background during IT

lib/pangea/models/practice_activities.dart/practice_activity_record_model.dart
=> cast score as int before sending to the server

lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/overlay_message.dart
=> Scrollable overlay message

lib/pages/chat/chat.dart, lib/pangea/widgets/chat/message_selection_overlay.dart
=> Overlay reactions

lib/pangea/controllers/practice_activity_generation_controller.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> Use activity model directly

lib/pangea/widgets/chat/message_unsubscribed_card.dart
=> clear selected messages when showing paywall

lib/pangea/constants/local.key.dart, lib/pangea/controllers/practice_activity_record_controller.dart, lib/pangea/matrix_event_wrappers/pangea_message_event.dart, lib/pangea/matrix_event_wrappers/practice_activity_event.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> cache number of completed activities

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pangea/utils/instructions.dart, lib/pangea/utils/overlay.dart
=> Default overlay blur

lib/pangea/utils/inline_tooltip.dart
=> center text in inline tooltip

lib/pages/chat_list/space_view.dart, lib/pages/new_space/new_space.dart, lib/pages/user_bottom_sheet/user_bottom_sheet.dart
=> preset all new room to public to disable encryption

lib/pangea/controllers/practice_activity_generation_controller.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> Locked toolbar bug

lib/pages/chat/events/audio_player.dart
=> prevent audio player text from being split onto multiple lines

lib/pages/chat/chat.dart, lib/pangea/choreographer/controllers/igc_controller.dart, lib/pangea/widgets/igc/pangea_text_controller.dart
=> Testing fixes

lib/pangea/widgets/igc/span_card.dart
=> moves scrollbar to side of span card

lib/utils/show_update_snackbar.dart
=> decreased duration of updated version snackbar

lib/pages/settings/settings_view.dart
=> added onTap to version number in settings to copy on click

lib/pangea/widgets/content_issue_button.dart
=> Make content issue dialog scrollable to prevent overflow

lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/client_chooser_button.dart
=> initial work to bring back search bar

lib/pangea/extensions/pangea_event_extension.dart, lib/pangea/widgets/chat/message_audio_card.dart, lib/pangea/widgets/chat/tts_controller.dart
=> added fix for different map keys in voices across platforms

lib/pangea/widgets/conversation_bot/conversation_bot_mode_dynamic_zone.dart, lib/pangea/widgets/conversation_bot/conversation_bot_mode_select.dart, lib/pangea/widgets/conversation_bot/conversation_bot_settings.dart, lib/pangea/widgets/conversation_bot/conversation_bot_settings_form.dart, lib/pangea/widgets/space/language_level_dropdown.dart
=> Bot settings design

lib/pages/chat/chat.dart, lib/pages/new_space/new_space.dart, lib/pangea/controllers/pangea_controller.dart, lib/pangea/widgets/chat/message_audio_card.dart, lib/pangea/widgets/chat/message_translation_card.dart, lib/pangea/widgets/chat/tts_controller.dart, lib/pangea/widgets/igc/card_error_widget.dart, lib/pangea/widgets/igc/card_header.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> Sentry issues

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/no_more_practice_card.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> dynamic sizing for practice activity toolbar content

assets/l10n/intl_en.arb, lib/pages/chat_list/client_chooser_button.dart, lib/pages/new_group/new_group_view.dart
=> copyeditting and updated order of main menu options

lib/pages/chat_list/space_view.dart, lib/pangea/utils/overlay.dart
=> adjust oerlay offset on overflow

lib/config/routes.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pages/settings/settings_view.dart, lib/pangea/choreographer/widgets/language_permissions_warning_buttons.dart, lib/pangea/pages/settings_learning/settings_learning.dart, lib/pangea/pages/settings_learning/settings_learning_view.dart, lib/pangea/utils/find_conversation_partner_dialog.dart, lib/widgets/chat_settings_popup_menu.dart
=> always show learning settings in popup

lib/pangea/controllers/practice_activity_record_controller.dart, lib/pangea/matrix_event_wrappers/pangea_message_event.dart, pubspec.yaml
=> store num completed activities in memory instead of local cache

lib/pangea/choreographer/widgets/choice_array.dart, pubspec.yaml
=> Freezing fixes

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, pubspec.yaml
=> turn back on setState on analytics data

lib/pangea/choreographer/widgets/choice_array.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, pubspec.yaml
This reverts commit 59682599a5a6a3b5d3109cd44d1c10a512cae369.
- [ ] Every new feature in the app or the build system has a strategy how this will be tested and maintained from now on for every …
=> Revert "turn off choice array animation"

lib/config/app_config.dart, lib/pages/chat/events/audio_player.dart, lib/pangea/utils/inline_tooltip.dart, lib/pangea/widgets/chat/message_audio_card.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_speech_to_text_card.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_translation_card.dart, lib/pangea/widgets/chat/message_unsubscribed_card.dart, lib/pangea/widgets/chat/toolbar_content_loading_indicator.dart, lib/pangea/widgets/common_widgets/overlay_container.dart, lib/pangea/widgets/igc/card_error_widget.dart, lib/pangea/widgets/igc/card_header.dart, lib/pangea/widgets/igc/word_data_card.dart, lib/pangea/widgets/practice_activity/no_more_practice_card.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart, lib/pangea/widgets/select_to_define.dart, pubspec.yaml
=> Toolbar min dimensions

lib/pangea/widgets/chat/message_audio_card.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/tts_controller.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart, lib/pangea/widgets/practice_activity/word_audio_button.dart, pubspec.yaml
=> only init one instance of ttscontroller, don't stop tts twice

pubspec.yaml
=> comment out env file paths in pubspec

lib/pangea/widgets/chat/message_selection_overlay.dart
=> removed print statement

lib/pages/chat/chat.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart, lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/choreographer/controllers/igc_controller.dart, lib/pangea/choreographer/controllers/it_controller.dart, pubspec.yaml
=> Dont combine it and igc

lib/main.dart
=> commenting out code to logout on server mixup until tested further

lib/main.dart
=> fixed error in server mixup test

lib/pangea/widgets/conversation_bot/conversation_bot_settings.dart
Create bot options before inviting it over, otherwise it's gonna freak out and leave 🙄
=> create bot options before invite

lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/widgets/chat/message_toolbar.dart
Addressing the issue of not being able to send without running IGC. Should discuss though.
=> allow sending if in manual igc mode

lib/pages/chat/chat.dart, lib/pages/chat/events/message.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pangea/enum/instructions_enum.dart, lib/pangea/utils/inline_tooltip.dart, lib/pangea/utils/instructions.dart
=> don't call fetchOwnProfile is userID is null

lib/pages/settings_security/settings_security.dart, lib/pangea/controllers/subscription_controller.dart, lib/pangea/controllers/user_controller.dart, lib/pangea/models/base_subscription_info.dart, lib/pangea/models/mobile_subscriptions.dart, lib/pangea/models/web_subscriptions.dart, lib/pangea/pages/p_user_age/p_user_age.dart, lib/pangea/pages/settings_subscription/settings_subscription.dart, lib/pangea/pages/settings_subscription/settings_subscription_view.dart, lib/pangea/repo/subscription_repo.dart, lib/pangea/utils/subscription_app_id.dart, lib/pangea/widgets/chat/message_unsubscribed_card.dart, lib/pangea/widgets/igc/paywall_card.dart, lib/pangea/widgets/subscription/subscription_buttons.dart, lib/pangea/widgets/subscription/subscription_options.dart
=> some refactoring to subscriptions, added auto 1-day pretrial

lib/pangea/controllers/subscription_controller.dart
=> call setCustomerSubscription after configuring subscription info

lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/choreographer/controllers/igc_controller.dart, lib/pangea/constants/model_keys.dart, lib/pangea/models/user_model.dart, lib/pangea/pages/settings_learning/settings_learning_view.dart, lib/pangea/widgets/igc/pangea_text_controller.dart, lib/pangea/widgets/igc/span_card.dart
=> set auto-play IT to true by default

lib/pangea/utils/inline_tooltip.dart
=> allow text to wrap in inline tooltips

lib/pangea/widgets/chat/missing_voice_button.dart
=> restrict width of missing voice button

lib/pangea/choreographer/widgets/it_bar.dart
=> don't allow user to chose the incorrect choices in IT

lib/pages/chat/chat_input_row.dart, lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/choreographer/controllers/it_controller.dart, lib/pangea/choreographer/widgets/send_button.dart, lib/pangea/enum/edit_type.dart, lib/pangea/widgets/chat/missing_voice_button.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/word_audio_button.dart
=> start language assistance on enter

lib/pangea/widgets/chat/overlay_message_text.dart, lib/pangea/widgets/chat/tts_controller.dart
=> Sentry issue fixes

lib/pages/chat_list/chat_list_body.dart, lib/pages/chat_list/chat_list_header.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pangea/widgets/animations/progress_bar/level_bar.dart, lib/pangea/widgets/animations/progress_bar/progress_bar.dart, lib/pangea/widgets/animations/progress_bar/progress_bar_details.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart, lib/pangea/widgets/chat_list/analytics_summary/progress_indicator.dart, lib/pangea/widgets/chat_list/pangea_chat_list_header.dart
=> updates to main menu design

lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart
=> enable other toolbar buttons in message not in l2

lib/pangea/controllers/practice_activity_generation_controller.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart, pubspec.yaml
=> redact the current activity event when submitting feedback

lib/config/app_config.dart, lib/pangea/enum/message_mode_enum.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart, lib/pangea/widgets/pressable_button.dart
=> added press animations to toolbar buttons

lib/pages/chat/chat_input_row.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/overlay_footer.dart, lib/pangea/widgets/chat/overlay_header.dart, lib/pangea/widgets/chat/pangea_reaction_picker.dart
=> Reorder chat options

lib/pages/chat/chat_input_row.dart
=> added back record button

lib/pangea/widgets/chat/message_selection_overlay.dart
=> revent change to padding in message overlay

lib/pangea/widgets/pressable_button.dart
=> keep button down if disabled

lib/config/app_config.dart, lib/pangea/utils/bot_style.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/chat/message_translation_card.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> 925 change bot style text to use same font as messages set toolbar min width and height based on audio activity

lib/pangea/controllers/get_analytics_controller.dart, lib/pangea/controllers/put_analytics_controller.dart, lib/pangea/enum/construct_type_enum.dart, lib/pangea/enum/progress_indicators_enum.dart, lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/models/analytics/constructs_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/widgets/animations/gain_points.dart, lib/pangea/widgets/chat_list/analytics_summary/analytics_popup/analytics_popup.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_bar.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart, lib/pangea/widgets/chat_list/analytics_summary/level_badge.dart, lib/pangea/widgets/chat_list/analytics_summary/progress_indicator.dart, lib/pangea/widgets/practice_activity/target_tokens_controller.dart, pubspec.yaml
=> update ConstructListModel to get all analytics metrics

lib/pages/chat/events/audio_player.dart
=> fix audio overflow

lib/pages/chat/chat.dart, lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/controllers/language_controller.dart
=> don't call grammar_lite if l1 or l2 are unknown

lib/pages/chat_list/chat_list.dart, lib/pangea/controllers/class_controller.dart, lib/pangea/controllers/get_analytics_controller.dart, lib/pangea/controllers/pangea_controller.dart, lib/pangea/controllers/put_analytics_controller.dart, lib/pangea/pages/sign_up/signup.dart, lib/pangea/utils/download_chat.dart, lib/pangea/widgets/chat/overlay_message_text.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart
=> reset room in startBotChat function after waiting for it in sync

lib/pages/chat_details/chat_details.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_list/space_view.dart, lib/pangea/widgets/chat/add_room_dialog.dart, lib/pangea/widgets/chat/visibility_toggle.dart
=> 934 enrolling users automatically in several spaces

assets/l10n/intl_en.arb, lib/pangea/choreographer/widgets/it_bar.dart, lib/pangea/enum/instructions_enum.dart, lib/pangea/models/user_model.dart, lib/pangea/utils/instructions.dart
=> added new IT instruction tooltip

lib/pangea/matrix_event_wrappers/pangea_message_event.dart
=> if pangea rep is null, still get and save text to speech event

lib/pages/chat/events/message_content.dart
=> make all message content text styles equal height

lib/pangea/constants/local.key.dart, lib/pangea/controllers/subscription_controller.dart, lib/pangea/models/base_subscription_info.dart, lib/pangea/repo/subscription_repo.dart, lib/pangea/utils/subscription_app_id.dart
=> locally cache subscription info

lib/main.dart, lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/models/analytics/constructs_model.dart, lib/pangea/models/pangea_token_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/widgets/chat/message_selection_overlay.dart
=> manage getting construct uses with category 'other'

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> center activities in toolbar properly

lib/pangea/controllers/subscription_controller.dart
=> check for trial update when getting isSubscribed

lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/overlay_footer.dart, lib/pangea/widgets/chat/overlay_header.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> added border radius to overlay header

lib/pangea/controllers/get_analytics_controller.dart, lib/pangea/models/analytics/constructs_model.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart
=> fix getCategory function

lib/pangea/widgets/chat/message_token_text.dart
=> make underlines match the exact width of the text they're hiding

lib/pangea/utils/instructions.dart, lib/pangea/widgets/chat/missing_voice_button.dart, lib/pangea/widgets/chat/tts_controller.dart, pubspec.yaml
=> more error logging for tts

lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/overlay_header.dart, lib/pangea/widgets/igc/word_data_card.dart
=> 1035 cant scroll down the definition box

lib/pangea/models/bot_options_model.dart
=> account for pre-1a difficulty in bot options fromJson method

.env, .gitignore, README.md, assets/.env
=> 944 publish env

lib/pages/chat/chat.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart, lib/pangea/widgets/pressable_button.dart
=> call hapticfeedback.vibrate on iOS

lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/models/analytics/construct_use_model.dart, lib/pangea/models/analytics/constructs_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/utils/grammar/get_grammar_copy.dart, lib/pangea/widgets/chat_list/analytics_summary/analytics_popup/analytics_popup.dart
=> group together 'other' category with more specific categories

lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/models/analytics/construct_use_model.dart, lib/pangea/models/analytics/constructs_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/utils/grammar/get_grammar_copy.dart, lib/pangea/widgets/chat_list/analytics_summary/analytics_popup/analytics_popup.dart
Reverts pangeachat/client#1026
=> Revert "group together 'other' category with more specific categories"

lib/pages/chat/chat.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart, lib/pangea/widgets/pressable_button.dart
=> remove haptic feedback on iOS

lib/pages/chat/events/message_content.dart, lib/pangea/widgets/chat/message_selection_overlay.dart
=> fixes for overlay offset on mobile

lib/pangea/choreographer/controllers/it_controller.dart, lib/pangea/widgets/chat/message_selection_overlay.dart
=> more overlay positioning fixes

assets/l10n/intl_en.arb
=> update copy for inviting users by link or code

assets/l10n/intl_en.arb, pubspec.yaml
=> 1050 add users by link or code

lib/pangea/widgets/chat/tts_controller.dart, lib/pangea/widgets/practice_activity/word_audio_button.dart, lib/pangea/widgets/practice_activity/word_focus_listening_activity.dart, lib/utils/platform_infos.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
=> added alternative tts package for windows users

lib/pangea/choreographer/widgets/start_igc_button.dart
=> show language settings dialog on press start IGC button if text is empty

lib/pages/chat/input_bar.dart, lib/pangea/utils/overlay.dart
=> fixed span card overflowing

lib/config/app_config.dart, lib/pages/chat/events/message_content.dart, lib/pangea/utils/bot_style.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_translation_card.dart, lib/pangea/widgets/chat/overlay_message.dart, lib/pangea/widgets/igc/card_error_widget.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> 1053 making font in the tool pop up the same size as message

lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart
=> increased height of level badge

assets/l10n/intl_en.arb, lib/pages/chat/chat_view.dart, lib/pages/chat_list/chat_list.dart, lib/pangea/pages/chat_details/pangea_chat_details.dart, lib/widgets/chat_settings_popup_menu.dart
Assigning to you to check that I got all the instances of the chat details icon. I think I did.
=> changing mute and chat details icons

lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart
=> fix positioning of popups over input bar

lib/pages/chat/chat_input_row.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/overlay_footer.dart
=> added spacing when overlay has footer overflow

lib/pangea/widgets/chat_list/analytics_summary/analytics_popup/analytics_popup.dart
=> added PageStorageKey to categories list to maintain its scroll position

lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_settings_button.dart
=> don't use null check operator on user l2

assets/l10n/intl_en.arb
=> updated copy

lib/pages/chat_list/chat_list.dart, pubspec.lock
=> call context.go to rooms when clearing active space

lib/pangea/widgets/chat/visibility_toggle.dart
=> set value of searchability toggle to room visibility

lib/pangea/choreographer/widgets/it_bar.dart, lib/pangea/utils/inline_tooltip.dart, lib/pangea/widgets/chat/message_speech_to_text_card.dart
=> fix speech-to-text inline tooltip overflow

lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/widgets/chat/message_translation_card.dart
=> if totalXP calculation is negative, reset to 0

.env, assets/.env, lib/pages/chat/chat.dart, lib/pages/chat_details/chat_details.dart, lib/pages/chat_list/chat_list.dart, lib/pangea/config/environment.dart, lib/pangea/constants/model_keys.dart, lib/pangea/controllers/pangea_controller.dart, lib/pangea/models/user_model.dart, lib/pangea/pages/chat_details/pangea_chat_details.dart
=> initial work on auto-enroll users in support space

lib/pangea/choreographer/widgets/choice_array.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, pubspec.yaml
=> don't play individual audios while main audio is playing

lib/pages/chat/events/message_content.dart, lib/pages/chat_list/chat_list_view.dart, lib/pangea/matrix_event_wrappers/pangea_representation_event.dart, lib/pangea/widgets/chat/chat_list_view_body_wrapper.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> Testing updates

assets/l10n/intl_en.arb, lib/pages/chat_list/chat_list.dart, lib/pages/new_group/new_group_view.dart, lib/pages/new_space/new_space.dart, lib/pages/new_space/new_space_view.dart, lib/pangea/extensions/pangea_room_extension/pangea_room_extension.dart, lib/pangea/extensions/pangea_room_extension/room_children_and_parents_extension.dart, lib/pangea/pages/chat_details/pangea_chat_details.dart, lib/pangea/widgets/chat/add_room_dialog.dart, lib/pangea/widgets/chat/visibility_toggle.dart
=> 1137 room visibility changes

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> 1134 sound still playing when flagging an item

lib/pages/chat/input_bar.dart
=> uncomment typeaheadfield

lib/pangea/models/space_model.dart, lib/pangea/models/user_model.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> Dont play tokens on flag activity

.github/workflows/release.yaml
=> copy .env file before production release

.github/workflows/release.yaml
=> More gh actions fixes

.gitignore, lib/pangea/config/environment.dart, pubspec.yaml
=> don't pull support space IDs from .env file

lib/pangea/config/environment.dart, pubspec.yaml
=> string replace end of choreo url

lib/pages/chat_list/space_view.dart
=> more accurate chat count in space view

lib/pangea/controllers/pangea_controller.dart
=> don't auto-join support space

assets/l10n/intl_en.arb, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/space_view.dart, lib/pangea/extensions/pangea_room_extension/room_children_and_parents_extension.dart, lib/pangea/widgets/chat/add_room_dialog.dart
=> prevent users from nesting spaces

lib/pages/chat/chat.dart, lib/pages/chat/chat_event_list.dart, lib/pages/chat/events/message.dart, lib/pangea/widgets/pressable_button.dart
=> make first message not from the user in a chat a pressable button

lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_toolbar.dart
=> go straight to translation if message not in target language

linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
=> fix android build

assets/l10n/intl_en.arb, lib/pages/new_group/new_group_view.dart
=> new room copy updates

.env, .gitignore, assets/.env
=> added .env file back to repo

assets/l10n/intl_en.arb, lib/widgets/public_room_bottom_sheet.dart
=> added option to join space with code in public room bottom sheet

lib/widgets/unread_rooms_badge.dart
=> exclude analytics rooms from notification counts

lib/widgets/public_room_bottom_sheet.dart
=> Change share link to pangea chat

lib/utils/background_push.dart
=> open roomID on click notification

assets/l10n/intl_en.arb, lib/pangea/controllers/get_analytics_controller.dart, lib/pangea/enum/construct_use_type_enum.dart, lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/widgets/animations/progress_bar/animated_level_dart.dart, lib/pangea/widgets/animations/progress_bar/progress_bar.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_bar.dart, lib/pangea/widgets/chat_list/analytics_summary/learning_progress_indicators.dart, lib/pangea/widgets/chat_list/analytics_summary/level_bar_popup.dart
=> added level bar popup with XP, level, and recent construct use info

assets/l10n/intl_en.arb, lib/pangea/models/analytics/construct_list_model.dart, lib/pangea/widgets/chat_list/analytics_summary/level_bar_popup.dart
=> only show 100 most recent uses in level bar popup

lib/pangea/controllers/language_controller.dart, lib/pangea/widgets/user_settings/p_language_dialog.dart
=> in stateful builder use context instead of outside context

lib/pangea/controllers/language_controller.dart, lib/pangea/widgets/user_settings/p_language_dialog.dart
=> if user doesn't have l1, return system lang

lib/widgets/public_room_bottom_sheet.dart
=> only show option to enter code if room is space

lib/pangea/controllers/language_controller.dart
=> if user l1 is not set, return system language

lib/pangea/controllers/language_controller.dart, lib/pangea/controllers/language_list_controller.dart, lib/pangea/extensions/pangea_room_extension/room_space_settings_extension.dart, lib/pangea/widgets/user_settings/p_language_dialog.dart
=> made PangeaLanguage.byLangCode nullable

lib/pangea/controllers/app_version_controller.dart
=> if version is bigger, don't account for build name

lib/pangea/enum/construct_use_type_enum.dart, lib/pangea/widgets/chat_list/analytics_summary/level_bar_popup.dart
=> updates to level bar popup design

assets/l10n/intl_en.arb, lib/pangea/controllers/app_version_controller.dart
=> added version numbers to update dialog

lib/pages/chat/events/html_message.dart, lib/pangea/models/igc_text_data_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/widgets/igc/pangea_text_controller.dart, pubspec.lock, pubspec.yaml
=> improved logging for acceptReplacement index error

lib/pages/chat_list/chat_list_body.dart
=> added scroll bars to search results

lib/pages/chat/chat_app_bar_title.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/events/room_creation_state_event.dart, lib/pages/chat/seen_by_row.dart, lib/pages/chat/typing_indicators.dart, lib/pages/chat_details/chat_details_view.dart, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_item.dart, lib/pages/chat_list/chat_list_view.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pages/chat_list/space_view.dart, lib/pages/chat_list/status_msg_list.dart, lib/pages/chat_search/chat_search_message_tab.dart, lib/pages/settings/settings_view.dart, lib/pages/settings_ignore_list/settings_ignore_list_view.dart, lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart, lib/pangea/pages/chat_details/pangea_chat_details.dart, lib/pangea/utils/bot_name.dart, lib/pangea/widgets/common/bot_face_svg.dart, lib/widgets/avatar.dart, lib/widgets/profile_bottom_sheet.dart
Adds animation to avatars for bots and bot DMs
Animation resets at random times 20-30 seconds from animation start
=> Bot animations

assets/l10n/intl_en.arb, lib/pages/login/login.dart, lib/pages/login/login_view.dart, lib/pangea/constants/local.key.dart, lib/pangea/controllers/language_controller.dart, lib/pangea/pages/connect/p_sso_button.dart, lib/pangea/pages/sign_up/full_width_button.dart, lib/pangea/pages/sign_up/login_or_signup_view.dart, lib/pangea/pages/sign_up/pangea_login_scaffold.dart, lib/pangea/pages/sign_up/pangea_login_view.dart, lib/pangea/pages/sign_up/signup_view.dart, lib/pangea/pages/sign_up/signup_with_email_view.dart, lib/pangea/pages/sign_up/user_settings.dart, lib/pangea/pages/sign_up/user_settings_view.dart, lib/pangea/utils/sso_login_action.dart, lib/pangea/widgets/pressable_button.dart, lib/pangea/widgets/signup/tos_checkbox.dart, lib/pangea/widgets/user_settings/p_language_dropdown.dart
=> Login signup fixes

.github/workflows/main_deploy.yaml, .github/workflows/manual.yml, .github/workflows/release.yaml, .gitignore, pubspec.yaml, scripts/enable_mobile_env.patch
Added patch to uncomment the .env from pubspec.
Moved the android release to manual
=> added patch and moved to manual

lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/choreographer/widgets/start_igc_button.dart, lib/pangea/enum/assistance_state_enum.dart
Shows paywall card when no-subscription user clicks IGC button
=> Paywall on IGC click

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/word_zoom/word_zoom_widget.dart
=> fix for mobile layout issues on mobile

assets/l10n/intl_en.arb, lib/pangea/pages/settings_learning/settings_learning.dart, lib/pangea/pages/settings_learning/settings_learning_view.dart
=> add back public profile toggle to learning settings

lib/pangea/pages/settings_learning/settings_learning.dart
=> public profile toggle sets user DOB

lib/pages/login/login.dart, lib/pangea/pages/connect/p_sso_button.dart, lib/pangea/pages/sign_up/full_width_button.dart, lib/pangea/pages/sign_up/signup.dart, lib/pangea/pages/sign_up/signup_with_email_view.dart, lib/pangea/pages/sign_up/user_settings.dart, lib/pangea/pages/sign_up/user_settings_view.dart, lib/pangea/widgets/pressable_button.dart, lib/pangea/widgets/signup/tos_checkbox.dart
=> Signup login updates

assets/l10n/intl_en.arb, lib/pangea/constants/morph_categories_and_labels.dart, lib/pangea/models/practice_activities.dart/practice_activity_record_model.dart, lib/pangea/repo/lemma_definition_repo.dart, lib/pangea/repo/practice/practice_repo.dart, lib/pangea/repo/practice/word_meaning_activity_generator.dart, lib/pangea/widgets/chat/message_audio_card.dart, lib/pangea/widgets/chat/message_selection_overlay.dart, lib/pangea/widgets/chat/message_token_text.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/igc/card_error_widget.dart, lib/pangea/widgets/practice_activity/emoji_practice_button.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart, lib/pangea/widgets/practice_activity/word_zoom_activity_button.dart, lib/pangea/widgets/word_zoom/contextual_translation_widget.dart, lib/pangea/widgets/word_zoom/lemma_widget.dart, lib/pangea/widgets/word_zoom/morphological_widget.dart, lib/pangea/widgets/word_zoom/word_zoom_widget.dart
=> fix: simplify word zoom card, make all activity buttons stateless

lib/pages/chat/events/message.dart, lib/pages/chat/events/message_content.dart, lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/controllers/app_version_controller.dart, lib/pangea/widgets/chat/message_toolbar_buttons.dart, lib/pangea/widgets/pressable_button.dart
=> fix: don't play button click sound on click message button

lib/pangea/widgets/pressable_button.dart
=> fix: give pressable buttons constant height

lib/pages/chat/events/message_content.dart, lib/pangea/widgets/chat/overlay_message.dart
=> fix: make overlay accurate for message with edits and replies

assets/l10n/intl_en.arb, lib/pangea/choreographer/widgets/choice_array.dart, lib/pangea/repo/lemma_definition_repo.dart, lib/pangea/repo/practice/word_meaning_activity_generator.dart, lib/pangea/widgets/chat/message_toolbar.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart, lib/pangea/widgets/word_zoom/contextual_translation_widget.dart, lib/pangea/widgets/word_zoom/word_zoom_widget.dart
=> 1337 feedback on word card

lib/pangea/models/practice_activities.dart/practice_activity_model.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> fix: don't play activity target tokens on init

assets/l10n/intl_en.arb, lib/pangea/constants/morph_categories_and_labels.dart, lib/pangea/repo/practice/lemma_activity_generator.dart, lib/pangea/repo/practice/practice_repo.dart, lib/pangea/widgets/word_zoom/lemma_widget.dart, lib/pangea/widgets/word_zoom/word_zoom_widget.dart
=> feat: show lemma under token, give lemma activity first if applicable

lib/pangea/choreographer/widgets/choice_array.dart, lib/pangea/controllers/put_analytics_controller.dart, lib/pangea/models/pangea_token_model.dart, lib/pangea/models/practice_activities.dart/practice_activity_record_model.dart, lib/pangea/repo/practice/emoji_activity_generator.dart, lib/pangea/widgets/practice_activity/emoji_practice_button.dart, lib/pangea/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/widgets/practice_activity/practice_activity_card.dart
=> feat: always show emoji activity, enable use to update emoji choice

pubspec.lock, pubspec.yaml
=> fix(deps): update flutter_secure_storage package

lib/pangea/utils/message_text_util.dart, lib/pangea/widgets/chat/message_token_text.dart
=> fix: if messageDisplayRepresentation is null, display event body

lib/pangea/utils/grammar/get_grammar_copy.dart
=> fix: add copy for common noun type morph tag

lib/pangea/models/pangea_token_model.dart, lib/pangea/widgets/word_zoom/word_zoom_widget.dart
=> 1371 staging bug or maybe technical design issue with morph choices

lib/pangea/widgets/download_analytics_dialog.dart
=> fix: include space admin analytics in space analytics download

lib/pangea/utils/get_chat_list_item_subtitle.dart, lib/pangea/widgets/chat/message_token_text.dart
=> fix: Limit message preview to one line

lib/config/app_config.dart, lib/pages/chat/chat_input_row.dart, lib/pages/chat/input_bar.dart, lib/pages/settings_chat/settings_chat_view.dart
=> feat: uncomment sendOnEnter chat setting

lib/pangea/models/analytics/analytics_summary_model.dart, lib/pangea/models/analytics/construct_list_model.dart
=> fix: get morph copy for all morph lists in analytics download

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> fix: remove maxWidth constraint from multiple choice activity card

lib/pangea/matrix_event_wrappers/pangea_message_event.dart
=> fix: prevent proportion from being negative. If negative, return 0

lib/pangea/matrix_event_wrappers/pangea_message_event.dart
=> fix: fix proportion calculation

lib/pangea/widgets/word_zoom/lemma_meaning_widget.dart
=> fix: fix overflow for long lemma definitions

lib/pangea/widgets/practice_activity/multiple_choice_activity.dart
=> fix: replace maxWidth in multiple choice activity

lib/pangea/choreographer/widgets/send_button.dart
=> feat: disable send button if fetching IGC

lib/pangea/extensions/pangea_room_extension/room_analytics_extension.dart
=> fix: don't error out of analytics download on space hierarchy error

lib/pages/chat_list/chat_list.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> fix: make scrollbar in morph_center_widget scrollable

lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> fix: add padding inside morph choices scroll view

lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart
=> feat: allow height of lemma correction text field to grow to 3 lines

lib/pangea/choreographer/models/igc_text_data_model.dart
=> feat: function to convert RepresentationEvent => IGCTextData

lib/pangea/events/utils/message_text_util.dart, lib/pangea/toolbar/widgets/message_token_text.dart, lib/pangea/toolbar/widgets/overlay_message.dart
Reverts pangeachat/client#1455
=> Revert "revert recent changes to relevant files to test if that fixes hidden …"

lib/config/app_config.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> fix: revent toolbar max height

lib/pangea/toolbar/widgets/practice_activity/multiple_choice_activity.dart
=> feat: sort distractors by text length

lib/pangea/toolbar/repo/morph_activity_generator.dart
=> fix: don't add question mark to end of morph activity question

lib/pangea/choreographer/controllers/igc_controller.dart
=> fix: don't hide message at end of IT

lib/pangea/toolbar/repo/practice_repo.dart, lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: don't highlight words while doing hwl activity

lib/pages/login/login.dart, lib/pages/login/login_view.dart, lib/pangea/login/pages/pangea_login_view.dart, lib/pangea/login/pages/signup.dart, lib/pangea/login/pages/signup_view.dart, lib/pangea/login/pages/signup_with_email_view.dart, lib/pangea/login/widgets/p_sso_button.dart
=> feat: stop other sso button loading if other sso button starts loading

lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> fix: fix overflows in lemma / morph correction overlay

lib/pangea/toolbar/models/practice_activity_model.dart, lib/pangea/toolbar/models/practice_activity_record_model.dart
=> 1485-too-many-points-for-lemma-meaning-activity

lib/pangea/events/models/pangea_token_model.dart
=> feat(lemma meaning activities): exclude proper nouns

lib/pangea/chat_settings/pages/pangea_chat_details.dart, lib/pangea/events/event_wrappers/pangea_message_event.dart, lib/pangea/events/models/pangea_token_model.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart
=> fix: only show space analytics download button on web

lib/pages/chat/chat_input_row.dart, lib/pangea/analytics/widgets/analytics_summary/level_bar_popup.dart, lib/pangea/chat_settings/widgets/conversation_bot/conversation_bot_settings_form.dart, lib/pangea/learning_settings/widgets/p_language_dropdown.dart
=> fix: don't overflow language options

lib/pangea/analytics/extensions/client_analytics_extension.dart, lib/pangea/toolbar/repo/lemma_meaning_activity_generator.dart, lib/pangea/toolbar/repo/practice_repo.dart, lib/widgets/presence_builder.dart
=> fix: fixes for sentry issues

lib/pangea/analytics/utils/get_svg_link.dart, lib/pangea/common/widgets/customized_svg.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_list_item.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_list_widget.dart
=> feat: widget for customizing SVG colors

assets/l10n/intl_en.arb, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> feat: updated morph correction copy

lib/config/app_config.dart, lib/pangea/analytics/constants/analytics_constants.dart, lib/pangea/analytics/enums/lemma_category_enum.dart, lib/pangea/analytics/models/construct_use_model.dart, lib/pangea/analytics/utils/get_svg_link.dart, lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_analytics_popup.dart, lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_definition_popup.dart, lib/pangea/common/widgets/customized_svg.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_list_item.dart
=> feat: replace XP level emojis with svgs

lib/pangea/toolbar/repo/lemma_meaning_activity_generator.dart
=> fix: cache boolean for whether or not meaning distractors are available

lib/pages/chat/events/html_message.dart, lib/pages/chat/events/message_content.dart
=> feat: add clicking for tokens in HTML messages

lib/pangea/analytics/extensions/client_analytics_extension.dart, lib/pangea/events/models/pangea_token_model.dart
=> fix: remove analyticsRoom getter from PangeaToken

lib/pages/chat/events/html_message.dart, lib/pangea/analytics/controllers/message_analytics_controller.dart
=> 1518 dont give hidden word activity for html formatted messages

lib/pangea/subscription/controllers/subscription_controller.dart, lib/pangea/subscription/models/base_subscription_info.dart, lib/pangea/subscription/widgets/subscription_buttons.dart, lib/pangea/subscription/widgets/subscription_options.dart
=> fix: remove duplicate trial option

lib/pangea/common/utils/any_state_holder.dart, lib/pangea/common/utils/overlay.dart, lib/pangea/instructions/instructions_show_popup.dart
=> fix: don't show multiple of the same instruction card

lib/pangea/toolbar/repo/lemma_activity_generator.dart
=> fix: if lemma not in choices list, add instead of replace

lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> fix: make morph/lemma edit tooltips more obvious

lib/pangea/events/models/pangea_token_model.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart
=> feat: add custom svgs to lemmas in word zoom card

lib/pages/chat/events/audio_player.dart, lib/pages/chat/events/message_content.dart, lib/pages/chat_list/chat_list.dart
=> fix: reset audio play on open toolbar

lib/pages/login/login.dart
=> fix: don't show duplicate login error

lib/pangea/toolbar/models/practice_activity_record_model.dart
=> dev: remove breakpoint

lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart, pubspec.yaml
=> fix: move tooltips inside flexible widgets to prevent freezing

lib/pangea/activity_planner/activity_plan_message.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart
=> fix: shrink lemma SVG in work zoom card

lib/utils/client_manager.dart
=> feat: exclude pin events from last room event

lib/pangea/activity_planner/activity_plan_message.dart, lib/pangea/toolbar/widgets/message_selection_positioner.dart
=> fix: fix message overflow for activity messages on mobile

lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_analytics_popup.dart, lib/pangea/common/widgets/customized_svg.dart, lib/pangea/toolbar/widgets/practice_activity/emoji_practice_button.dart, lib/pangea/toolbar/widgets/practice_activity/word_zoom_activity_button.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_list_item.dart
=> 1563-grammar-icon-in-light-mode

lib/widgets/public_room_bottom_sheet.dart
=> fix: don't show option to join with code if space is public

assets/l10n/intl_en.arb
=> fix: small copy update

lib/main.dart, lib/pangea/activity_planner/activity_list_view.dart, lib/pangea/activity_planner/activity_mode_list_repo.dart, lib/pangea/activity_planner/activity_plan_card.dart, lib/pangea/activity_planner/activity_plan_generation_repo.dart, lib/pangea/activity_planner/activity_plan_page_launch_icon_button.dart, lib/pangea/activity_planner/activity_planner_page.dart, lib/pangea/activity_planner/activity_planner_settings_search_widget.dart, lib/pangea/activity_planner/bookmarked_activities_repo.dart, lib/pangea/activity_planner/media_enum.dart, lib/pangea/activity_planner/suggestion_form_field.dart, lib/pangea/common/controllers/pangea_controller.dart, lib/pangea/extensions/pangea_room_extension.dart
=> fix: dart formatting

lib/pangea/common/controllers/pangea_controller.dart, lib/pangea/common/utils/p_store.dart
=> fix: clear lemma cache on logout and language change

lib/pages/chat/input_bar.dart
=> fix: use case insensitive match for replacing emoji

lib/pangea/activity_planner/activity_plan_message.dart
=> feat: update activity message background color

lib/pages/chat_details/chat_details.dart
=> fix: uncommented call to change room description

lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_analytics_popup.dart, lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_definition_popup.dart
=> fix: increased text size in vocab analytics popup

lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_definition_popup.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart
=> feat: trigger some tooltips on tap

assets/l10n/intl_en.arb, assets/l10n/intl_es.arb, lib/main.dart, lib/pangea/analytics/enums/construct_use_type_enum.dart, lib/pangea/toolbar/widgets/message_speech_to_text_card.dart
=> 1595-word-per-minute-is-still-not-accurate

lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_analytics_popup.dart
=> fix: increase padding in vocab analytics popup section

lib/pangea/common/constants/model_keys.dart
=> feat: update user cefr model key

lib/main.dart, lib/pages/chat/chat.dart, lib/pangea/activity_planner/activity_planner_page.dart, lib/pangea/activity_planner/suggestion_form_field.dart, lib/pangea/analytics/constants/morph_categories_and_labels.dart, lib/pangea/common/widgets/customized_svg.dart
=> fix: update text controller value when text field value changes

lib/pangea/events/models/pangea_token_model.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart, lib/pangea/toolbar/widgets/word_zoom/morphs/morphological_center_widget.dart, lib/pangea/toolbar/widgets/word_zoom/word_zoom_center_widget.dart
=> fix: on update POS morph feature, also update token's POS

lib/widgets/public_room_bottom_sheet.dart
=> fix: hide public room share link

lib/pages/chat/events/room_creation_state_event.dart, lib/pages/chat_list/chat_list_item.dart, lib/pangea/analytics/widgets/analytics_summary/vocab_analytics_popup/vocab_analytics_popup.dart, lib/pangea/bot/widgets/bot_face_svg.dart, lib/widgets/avatar.dart
=> Switch bot svg

pubspec.yaml
=> dev: bump version number

lib/widgets/unread_rooms_badge.dart
=> fix: revert change to how unread notification count is calculated

.github/workflows/issue_closed.yaml
=> feat: add github action to add needs testing labels to closed issues

.github/workflows/issue_closed.yaml, lib/pages/chat_list/chat_list.dart
=> 1653 GitHub action to add needs testing labels

lib/pangea/toolbar/widgets/practice_activity/emoji_practice_button.dart, lib/pangea/toolbar/widgets/practice_activity/word_text_with_audio_button.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_widget.dart, lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart
=> fix: resolve overflow for long lemmas

lib/pages/login/login.dart
=> feat: trim username and password fields before login

lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/learning_settings/pages/settings_learning_view.dart, lib/pangea/learning_settings/widgets/p_language_dropdown.dart
=> feat: move language dropdowns into learning settings dialog

lib/pages/chat/events/message.dart, lib/pages/chat/events/reply_content.dart, lib/pangea/activity_planner/activity_plan_message.dart, lib/pangea/toolbar/widgets/message_audio_card.dart, lib/pangea/toolbar/widgets/message_token_text.dart, lib/pangea/toolbar/widgets/overlay_message.dart
=> chore: update reply and link text styling

lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: reenable token clicking after adding linkify spans

lib/pages/chat/chat.dart, lib/pages/user_bottom_sheet/user_bottom_sheet_view.dart, lib/pangea/analytics_misc/get_analytics_controller.dart, lib/pangea/analytics_misc/put_analytics_controller.dart, lib/pangea/chat_list/utils/app_version_util.dart, lib/pangea/common/constants/model_keys.dart, lib/pangea/common/controllers/pangea_controller.dart, lib/pangea/events/constants/pangea_event_types.dart, lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/login/pages/signup.dart, lib/pangea/login/pages/user_settings.dart, lib/pangea/user/controllers/user_controller.dart, lib/pangea/user/models/profile_model.dart, lib/pangea/user/widgets/public_level_indicator.dart, pubspec.lock
=> 1547 level indicator for all users

lib/pages/chat/chat_input_row.dart, lib/pangea/toolbar/widgets/overlay_header.dart, lib/pangea/toolbar/widgets/pangea_reaction_picker.dart
=> feat: move reply button to chat view header

lib/pangea/login/pages/pangea_login_view.dart
=> fix: add back password reset button

lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/learning_settings/pages/settings_learning_view.dart, lib/pangea/learning_settings/widgets/country_picker_tile.dart, lib/pangea/learning_settings/widgets/p_language_dropdown.dart
=> feat: update country dropdown to match style of language dropdown

assets/l10n/intl_en.arb, lib/pangea/morphs/get_grammar_copy.dart
=> chore: add missing grammar copy

lib/pangea/learning_settings/widgets/country_picker_tile.dart
=> fix: remove expanded widget from country tile

assets/l10n/intl_en.arb
=> chore: update vocab copy

lib/pangea/learning_settings/pages/settings_learning_view.dart, lib/pangea/learning_settings/widgets/country_picker_tile.dart, lib/pangea/learning_settings/widgets/p_language_dropdown.dart, lib/pangea/learning_settings/widgets/p_settings_switch_list_tile.dart
=> chore: reduce padding in learning setting dropdowns

assets/l10n/intl_en.arb, assets/l10n/intl_es.arb, assets/l10n/intl_vi.arb, lib/pages/chat/chat_input_row.dart
=> chore: updated input bar copy

lib/pangea/learning_settings/utils/language_list_util.dart
=> fix: update out-of-date language cache

lib/pangea/morphs/morph_meaning/morph_info_repo.dart, lib/pangea/morphs/morph_meaning/morph_info_response.dart, lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: dispose TextPainter after use

lib/pangea/analytics_misc/construct_list_model.dart, lib/pangea/analytics_misc/get_analytics_controller.dart
=> fix: remove analytics from memory on logout

lib/pangea/analytics_summary/progress_indicator.dart, lib/pangea/analytics_summary/progress_indicators_enum.dart
=> feat: use custom vocab and morph icons

lib/pangea/analytics_details_popup/morph_analytics_view.dart, lib/pangea/analytics_details_popup/vocab_analytics_view.dart
=> feat: maintain scroll position in vocab/morph analytics view

lib/pangea/toolbar/controllers/tts_controller.dart
=> choreo: lower case text before tts

lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: more accurate splitting of tokens containing punctuation

lib/main.dart
=> fix: lock app in portrait mode

lib/pages/chat_list/chat_list.dart, lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: fix for splitting up tokens with combined punctuation

lib/pages/chat_list/chat_list_item.dart, lib/pages/chat_list/space_view.dart, lib/pangea/extensions/room_children_and_parents_extension.dart
=> fix: normalize space chat count copy

.github/workflows/release.yaml
creates a new release of the format "Release v[VERSION]" when a push to production happened.
Updates the live web version, but does not update applications
=> feat(github): GitHub production release flow

lib/pangea/analytics_summary/progress_indicator.dart
=> chore: revert updates to grammar icons in analytics summary

lib/pangea/common/constants/model_keys.dart, lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/user/controllers/user_controller.dart, lib/pangea/user/models/user_model.dart
=> fix: set profile to public by default

lib/pangea/toolbar/widgets/message_token_text.dart
=> fix: fix emoji rendering issues in message token text

lib/pangea/choreographer/models/igc_text_data_model.dart, lib/pangea/choreographer/repo/igc_repo.dart, lib/pangea/choreographer/repo/language_detection_repo.dart, lib/pangea/events/controllers/message_data_controller.dart, lib/pangea/events/event_wrappers/pangea_message_event.dart, lib/pangea/events/event_wrappers/pangea_representation_event.dart, lib/pangea/toolbar/widgets/message_selection_overlay.dart, lib/pangea/toolbar/widgets/message_token_text.dart, lib/pangea/toolbar/widgets/practice_activity/practice_activity_card.dart
=> feat: fetch new tokens for messages without originalsent representations

lib/pangea/learning_settings/pages/settings_learning_view.dart
=> fix: don't allow users to have same base and target short langCode

lib/pages/chat/events/html_message.dart, lib/pangea/toolbar/widgets/overlay_message.dart
=> fix: always show display event in toolbar

lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pangea/chat/widgets/chat_input_bar.dart, lib/pangea/chat/widgets/chat_input_bar_header.dart
=> fix: dynamically update input bar height to offset event list

lib/pages/chat/input_bar.dart
=> fix: delete selection are around input bar textfield

pubspec.yaml
=> chore: bump version number

assets/l10n/intl_en.arb, lib/pangea/analytics_summary/learning_progress_indicators.dart, lib/pangea/analytics_summary/progress_indicator.dart, pubspec.lock
=> feat: use text instead of icons for analytics buttons

assets/l10n/intl_en.arb, lib/pangea/choreographer/widgets/choice_array.dart, lib/pangea/common/utils/overlay.dart, lib/pangea/instructions/instructions_enum.dart, lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/learning_settings/pages/settings_learning_view.dart, lib/pangea/toolbar/controllers/tts_controller.dart, lib/pangea/toolbar/widgets/message_audio_card.dart, lib/pangea/toolbar/widgets/message_selection_overlay.dart, lib/pangea/toolbar/widgets/practice_activity/multiple_choice_activity.dart, lib/pangea/toolbar/widgets/practice_activity/word_audio_button.dart, lib/pangea/toolbar/widgets/practice_activity/word_text_with_audio_button.dart, lib/pangea/toolbar/widgets/word_zoom/word_zoom_widget.dart
=> 1846 word specific audio player not working

lib/widgets/future_loading_dialog.dart
=> fix: before popping in futureloadingdialog, check if canPop

lib/widgets/adaptive_dialogs/show_text_input_dialog.dart
=> fix: make text dialog autosubmit work as expected

lib/pangea/toolbar/widgets/message_toolbar.dart
=> chore: make textfields in toolbar work on firefox/safari

lib/pangea/morphs/morph_models.dart
=> fix: update key in MorphFeature.fromJson function

lib/pangea/analytics_summary/learning_progress_indicators.dart, lib/pangea/learning_settings/utils/language_list_util.dart, lib/pangea/toolbar/controllers/tts_controller.dart, lib/pangea/user/controllers/user_controller.dart
=> Mobile stt

lib/pangea/toolbar/widgets/message_meaning_card.dart, lib/pangea/toolbar/widgets/practice_activity/multiple_choice_activity.dart
=> chore: fix some spacing issues on small screens

lib/pangea/toolbar/widgets/practice_activity/multiple_choice_activity.dart
=> fix: removed duplicate question in activities

lib/pages/settings_security/settings_security.dart
=> fix: enable account deletion

lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/choreographer/widgets/igc/span_card.dart, lib/pangea/choreographer/widgets/translation_finished_flow.dart, lib/pangea/toolbar/widgets/practice_activity/practice_activity_card.dart
=> chore: when choices array goes off screen, stop playing TTS

lib/pangea/learning_settings/pages/settings_learning.dart, lib/pangea/toolbar/controllers/tts_controller.dart
=> fix: update logic for checking if short lang code TTS is available

lib/pages/chat/input_bar.dart
=> chore: set enableSuggestions to enableAutocorrect

lib/pangea/choreographer/controllers/choreographer.dart
=> chore: don't stop TTS after IT choice selection

.gitignore, assets/l10n/intl_vi.arb
=> chore: update Vietnamese translations

lib/pangea/analytics_details_popup/analytics_details_popup.dart
=> chore: remove analytics popup header text on mobile

assets/l10n/intl_en.arb, lib/pangea/chat_settings/pages/pangea_chat_details.dart
=> chore: update empty description copy for spaces

lib/pangea/extensions/room_events_extension.dart
=> fix: when leaving space, do not leave analytics rooms

assets/l10n/intl_en.arb, lib/pages/chat/chat.dart, lib/pangea/chat/widgets/event_too_large_dialog.dart, lib/pangea/extensions/room_events_extension.dart
=> feat: better UX for event too large error

lib/pangea/toolbar/widgets/message_selection_overlay.dart
=> chore: if originalSent without tokens, edit message to add new tokens

lib/pages/chat/events/audio_player.dart
=> chore: stop audio player on showToolbar

lib/pages/new_group/new_group.dart
=> chore: disable creation of space with empty name

lib/pages/chat/events/message.dart, lib/pangea/toolbar/widgets/message_token_text.dart, lib/pangea/toolbar/widgets/overlay_message.dart
=> chore: link visibility

lib/pages/chat_list/chat_list.dart, lib/pangea/events/event_wrappers/pangea_message_event.dart
=> chore: don't show toolbar for redacted messages

lib/pangea/common/controllers/pangea_controller.dart, lib/pangea/user/controllers/user_controller.dart
=> chore: clear init completer in userController on logout

lib/pangea/analytics_misc/level_display_name.dart
=> chore(level_display_name): don't display bot learning stuff

assets/l10n/intl_en.arb, assets/l10n/intl_vi.arb, lib/pages/chat_list/chat_list.dart, lib/pages/chat_list/chat_list_item.dart, lib/pangea/chat_settings/pages/pangea_chat_details.dart, lib/widgets/chat_settings_popup_menu.dart
=> chore: update leave room messages

lib/pages/chat_list/chat_list_body.dart
=> chore: add unread room badge to unread room filter

assets/l10n/intl_en.arb, lib/pages/chat_list/chat_list.dart, lib/pages/settings_security/settings_security.dart
=> chore: update copy in delete account dialog

lib/pages/chat_list/space_view.dart
=> chore: revert to fluffychat's add chat dialog

lib/pages/chat_list/space_view.dart
=> 2016 the confirm and cancel buttons not in the right place

lib/pages/chat_list/chat_list_body.dart
=> chore: show spaces filter if user is in any spaces

lib/config/routes.dart
=> fix: prevent rendering error on page resize

lib/pangea/subscription/controllers/subscription_controller.dart, lib/pangea/subscription/models/mobile_subscriptions.dart
=> chore: try to pull localized price string from revenuecat SDK on mobile

pubspec.yaml
=> build: bump version number

.vscode/settings.json, lib/pangea/analytics_details_popup/morph_details_view.dart, lib/pangea/analytics_details_popup/morph_meaning_widget.dart, lib/pangea/analytics_details_popup/vocab_details_view.dart, lib/pangea/morphs/morph_meaning/morph_info_repo.dart, lib/pangea/morphs/morph_meaning/morph_info_response.dart
=> feat: allow users to edit morph meanings

lib/pages/chat/chat.dart
=> chore: don't show overlay for redacted messages

lib/pages/chat/chat.dart, lib/pages/chat/chat_view.dart, lib/pangea/activity_planner/activity_plan_page_launch_icon_button.dart, lib/pangea/choreographer/controllers/choreographer.dart, lib/pangea/toolbar/controllers/tts_controller.dart
=> chore: stop audio when route changes and before playing token audio

lib/pages/chat/events/html_message.dart
=> chore: linkify HTML messages

lib/pages/chat/input_bar.dart
=> chore: only wrap input bar in selectionarea on web

lib/pangea/toolbar/reading_assistance_input_row/word_emoji_choice.dart, lib/pangea/toolbar/widgets/word_zoom/lemma_meaning_widget.dart
=> chore: fix app freezing in release mode

assets/l10n/intl_en.arb, lib/pages/chat_list/space_view.dart, lib/pangea/spaces/widgets/knocking_users_indicator.dart, lib/widgets/future_loading_dialog.dart, lib/widgets/public_room_bottom_sheet.dart
=> feat: notification in space view for knocking users

lib/pangea/analytics_misc/get_analytics_controller.dart, lib/pangea/analytics_misc/level_display_name.dart, lib/pangea/user/controllers/user_controller.dart, lib/pangea/user/models/profile_model.dart
=> 2006 target language information needs to be updated when users change

lib/config/app_config.dart, lib/pages/chat/chat_input_row.dart, lib/pangea/toolbar/reading_assistance_input_row/reading_assistance_input_bar.dart, lib/pangea/toolbar/widgets/message_selection_positioner.dart
=> chore: normalize footer height

lib/pages/chat_list/chat_list.dart
=> chore: exit chat when leaving via chat list item context menu

lib/pages/chat/chat.dart, lib/pages/chat_list/chat_list.dart
=> chore: stop audio on recording dialog

assets/l10n/intl_en.arb, lib/pages/chat_list/chat_list_body.dart, lib/pages/chat_list/client_chooser_button.dart, lib/pangea/spaces/utils/space_code.dart, lib/pangea/spaces/widgets/space_filter_buttons.dart, lib/widgets/navigation_rail.dart
=> feat: add join space button to space list / navigation bar

lib/widgets/public_room_bottom_sheet.dart
=> chore: fix provider error in public room sheet
